package deck

import "ulartangga/models"

// ActsOfServiceDeck berisi 100 kartu bahasa cinta Tindakan Pelayanan & Pengorbanan (50 Truth + 50 Dare)
// Dibagi ke dalam mode ONLINE (Video Call / LDR), OFFLINE (Ketemu Langsung), dan BOTH (Bisa Keduanya)
var ActsOfServiceDeck = []models.QuestionCard{
	// 50 TRUTH - ACTS OF SERVICE (ID 501 - 550)
	{501, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Pelayanan", "Bantuan kecil apa dariku yang tanpa kuminta paling sering membuat harimu terasa jauh lebih ringan?", false},
	{502, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Memori", "Momen saat aku merawatmu ketika kamu sedang sakit atau kelelahan, apa yang paling kamu ingat dari caraku menjagamu?", false},
	{503, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Tindakan nyata apa dariku yang paling membuatmu yakin bahwa aku benar-benar tulus menyayangimu?", false},
	{504, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Deep Talk", "Pekerjaan rumah atau urusan sehari-hari apa yang paling ingin kamu bagi bersamaku agar kamu tidak merasa sendirian?", false},
	{505, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Memori", "Ceritakan satu pengorbanan waktu atau tenagaku yang pernah membuatmu merasa sangat diperjuangkan!", false},
	{506, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Makanan", "Makanan atau minuman apa buatan/pesananku yang paling terasa seperti kehangatan rumah bagimu?", false},
	{507, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Apakah kamu lebih merasa dicintai saat aku mendengarkan keluh kesahmu atau saat aku langsung mencarikan solusinya?", false},
	{508, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Deep Talk", "Pernahkah kamu merasa lelah mengurus segala hal sendirian dan berharap aku lebih berinisiatif membantu?", false},
	{509, "TRUTH", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Kapan momen saat LDR di mana aku tiba-tiba berinisiatif memesankan makanan/obat saat kamu sakit yang paling bikin terharu?", false},
	{510, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Bagi kamu saat ketemu, apakah tindakan membukakan pintu, membawakan tas, atau memakaikan helm terasa sangat manis?", false},
	{511, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Hal sederhana apa yang kulakukan di pagi hari atau malam hari yang paling kamu rindukan saat kita berjauhan?", false},
	{512, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Deep Talk", "Bagaimana caramu menunjukkan rasa terima kasih ketika pasangan berusaha keras membantumu menyelesaikan masalah?", false},
	{513, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Memori", "Bantuan darurat apa yang pernah kuberikan padamu saat kamu sedang panik atau terjebak dalam masalah?", false},
	{514, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Apa kebiasaan baik dariku yang selalu memastikan kamu aman (misal: berjalan di sisi jalan yang aman / mengecek kendaraan)?", false},
	{515, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Saat kamu sedang suntuk bekerja, gestur perhatian kecil apa yang paling bisa mengembalikan fokus dan senyummu?", false},
	{516, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Deep Talk", "Apakah kamu tipe orang yang gengsi meminta tolong atau gampang mengekspresikan kebutuhan bantuanmu ke pasangan?", false},
	{517, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Makanan", "Pernahkah aku menyuapimu makanan saat tanganmu sedang repot? Bagaimana perasaanmu saat itu?", false},
	{518, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Memori", "Apa hal paling merepotkan yang pernah kulakukan demi membuatmu merasa nyaman dan senang?", false},
	{519, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Jika kamu sedang lelah sekali saat kita bersama, apakah kamu lebih ingin dipijat, dibuatkan makanan, atau ditemani tidur dalam hening?", false},
	{520, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Seberapa besar rasa lega yang kamu rasakan saat aku menawarkan diri: 'Biar ini aku aja yang urus ya'?", false},
	{521, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Deep Talk", "Tindakan pelayanan apa yang menurutmu menjadi bukti nyata cinta sejati dibanding ribuan kata manis?", false},
	{522, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Memori", "Momen perjalanan atau urusan bersama mana di mana kita saling bahu-membahu mengatasi kendala?", false},
	{523, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Apakah kamu merasa nyaman jika aku membantu merapikan barang-barang pribadi atau pakaianmu saat ketemu?", false},
	{524, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Kapan kamu merasa aku benar-benar melindungi martabat dan perasaanmu di depan orang banyak?", false},
	{525, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Deep Talk", "Apa kompromi terbesar yang pernah kulakukan demi menyesuaikan dengan kebutuhan atau kebiasaanmu?", false},
	{526, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Makanan", "Jika kita lelah sepulang kerja, masakan sederhana apa yang ingin kita masak bersama secara cepat di dapur?", false},
	{527, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Memori", "Pernahkah aku mengantarmu pulang dalam keadaan cuaca buruk atau larut malam? Apa yang kamu rasakan saat sampai di rumah?", false},
	{528, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Pelayanan", "Bagaimana caraku merawatmu ketika kamu sedang mengalami bad mood akibat PMS atau lelah pekerjaan?", false},
	{529, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Pernahkah kamu memperhatikan hal-hal detail yang kuselesaikan agar kamu tidak perlu khawatir?", false},
	{530, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Deep Talk", "Apa satu hal tentang pembagian peran rumah tangga masa depan yang paling ingin kita sepakati sejak sekarang?", false},
	{531, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Memori", "Ceritakan saat aku membantumu memilihkan barang atau menyelesaikan tugas sulit yang membuatmu bangga!", false},
	{532, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Apakah kamu lebih menyukai dijemput tepat waktu atau disiapkan bekal makanan saat bepergian?", false},
	{533, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Gestur refleks apa dariku yang tanpa kusadari selalu membuktikan rasa peduliku kepadamu?", false},
	{534, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Deep Talk", "Pernahkah kamu merasa perbuatan baikmu tidak dihargai olehku? Bagaimana kita bisa memperbaikinya?", false},
	{535, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Makanan", "Apa camilan favoritmu yang jika kubawakan/kupesankan tanpa diminta langsung membuat harimu bahagia?", false},
	{536, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Pelayanan", "Menurutmu, siapa di antara kita yang paling telaten dan sabar saat mengurus kebutuhan pasangan?", false},
	{537, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Memori", "Bantuan apa yang pernah kuberikan kepada keluargamu yang membuatmu semakin yakin pada komitmenku?", false},
	{538, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Kenapa tindakan nyata selalu terasa seribu kali lebih menenangkan bagimu dibanding janji di masa depan?", false},
	{539, "TRUTH", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Seberapa sering aku menelpon untuk membangunkanmu di pagi hari agar kamu tidak telat bangun saat LDR?", false},
	{540, "TRUTH", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Bantuan daring apa (misal: carikan info tiket, proofreading tulisan, edit file) yang pernah kuberikan yang paling berguna bagimu?", false},
	{541, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Ketika kamu memakai sepatu bertali atau membawa payung di tengah hujan, apa yang biasa kulakukan untukmu?", false},
	{542, "TRUTH", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Apakah kamu merasa terbantu saat aku mengingatkan jadwal minum obat atau vitamin lewat chat harian?", false},
	{543, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Deep Talk", "Bantuan seperti apa yang paling kamu butuhkan dariku saat pikiranmu sedang buntu dan kalut?", false},
	{544, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Perhatian", "Ketika kita makan di restoran ramai, hal apa yang kulakukan yang membuatmu tidak perlu repot sama sekali?", false},
	{545, "TRUTH", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Pernahkah aku begadang menemanimu lewat telepon sampai tugas atau skripsimu selesai semalaman?", false},
	{546, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Pelayanan", "Menurutmu, tindakan pelayanan apa yang paling ingin kamu persembahkan untuk pasanganmu setiap pagi?", false},
	{547, "TRUTH", "ACTS_OF_SERVICE", "OFFLINE", "Memori", "Saat kamu ketiduran di mobil atau di ruang tamu, bagaimana caraku memperlakukanmu agar tidurmu nyaman?", false},
	{548, "TRUTH", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Apa playlist lagu fokus atau pengantar tidur yang pernah kubuatkan untuk membantumu beristirahat?", false},
	{549, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Bagaimana caraku merespons ketika kamu mengeluh capek dengan rutinitas harianmu?", false},
	{550, "TRUTH", "ACTS_OF_SERVICE", "BOTH", "Komitmen", "Apa wujud pengabdian dan pelayanan cinta terbesar yang ingin kamu baktikan untuk masa depan rumah tangga kita?", false},

	// 50 DARE - ACTS OF SERVICE (ID 551 - 600)
	{551, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pijat", "Pijat lembut pundak dan tengkuk leher pasanganmu selama 1 menit penuh untuk melemaskan otot-ototnya yang tegang!", false},
	{552, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Minum", "Ambilkan segelas air putih hangat/dingin untuk pasanganmu dan suapkan langsung ke bibirnya dengan penuh kasih!", false},
	{553, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Kirimkan pesan pengingat minum air putih dan istirahat 5 menit sekarang juga lengkap dengan alasan kenapa kesehatannya sangat berharga!", false},
	{554, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Rapi", "Rapikan tatanan rambut, kerudung, atau kerah baju pasanganmu agar terlihat semakin rapi dan mempesona!", false},
	{555, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Bantu pasanganmu merancang to-do list 3 prioritas penting untuk harinya besok dan kirimkan dalam format rapi via chat!", false},
	{556, "DARE", "ACTS_OF_SERVICE", "BOTH", "Bantuan", "Tawarkan satu bantuan nyata yang bisa kamu selesaikan untuk pasanganmu malam ini atau besok pagi!", false},
	{557, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pijat", "Pijat lembut jari-jemari tangan pasanganmu satu per satu dari pangkal hingga ke ujung kuku selama 45 detik!", false},
	{558, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Setel alarm di HP-mu sendiri untuk menelpon dan membangunkan pasanganmu besok pagi tepat waktu!", false},
	{559, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Perhatian", "Bersihkan layar HP atau kacamata pasanganmu menggunakan kain halus sampai kinclong dan bersih!", false},
	{560, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Cari dan kirimkan artikel / tips relaksasi pereda stres terbaik di internet khusus untuk pasanganmu baca malam ini!", false},
	{561, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Kipaskan pasanganmu menggunakan buku/kipas selama 30 detik jika ruangan terasa hangat!", false},
	{562, "DARE", "ACTS_OF_SERVICE", "BOTH", "Bantuan", "Tanyakan 'Ada hal apa hari ini yang bikin kamu capek dan bisa aku bantu ringankan?' dan dengarkan baik-baik!", false},
	{563, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pijat", "Lakukan pijatan ringan di area pelipis dahi pasanganmu untuk membantu menghilangkan stres selama 30 detik!", false},
	{564, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Pesankan camilan atau minuman kesukaan pasanganmu lewat aplikasi antar online ke alamatnya sekarang!", false},
	{565, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Rapi", "Ambilkan barang yang sedang dibutuhkan pasangan di dekat kalian tanpa membiarkannya berdiri!", false},
	{566, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Makanan", "Suapkan satu gigitan makanan atau camilan manis ke mulut pasanganmu dengan tatapan penuh kelembutan!", false},
	{567, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Kirimkan tutorial gerakan peregangan leher/punggung (stretching) lewat chat dan bimbing pasanganmu melakukannya bersama di video call!", false},
	{568, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Ikatkan tali sepatu pasanganmu atau rapikan ujung celana/roknya dengan tulus!", false},
	{569, "DARE", "ACTS_OF_SERVICE", "BOTH", "Bantuan", "Janji untuk membantu mencucikan piring atau merapikan meja makan setelah sesi bermain game ini selesai!", false},
	{570, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Perhatian", "Pasangkan jaket, sweater, atau selimut ke tubuh pasanganmu agar dia merasa hangat dan terlindungi!", false},
	{571, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Bikin rekaman audio petunjuk meditasi / pernapasan relaksasi 30 detik untuk didengarkan pasanganmu sebelum tidur!", false},
	{572, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pijat", "Pijat lembut telapak kaki atau betis pasanganmu selama 1 menit jika kalian sedang duduk berdampingan santai!", false},
	{573, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Gendong pasanganmu (atau gandeng dan bimbing langkahnya dengan sangat hati-hati) melintasi ruangan!", false},
	{574, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Rapi", "Bantu rapikan barang-barang di tas atau meja belajar/kerja pasanganmu selama 1 menit!", false},
	{575, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Bantu cek prakiraan cuaca kota tempat tinggal pasangan untuk besok, lalu beri rekomendasi pakaian & payung yang perlu disiapkan!", false},
	{576, "DARE", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Tanyakan sisa persentase baterai HP pasangan, ingatkan untuk cas sebelum tidur dan jangan tidur di dekat colokan!", false},
	{577, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Minuman", "Bikin satu minuman hangat (teh manis, cokelat hangat, atau susu) khusus untuk pasanganmu!", false},
	{578, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Kirimkan link playlist suara hujan / white noise di Spotify atau YouTube untuk menemaninya tidur nyenyak!", false},
	{579, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Buka dan tutupkan pintu ruangan atau tarikkan kursi saat pasanganmu hendak duduk layaknya pelayanan bintang lima!", false},
	{580, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pijat", "Usap dan tepuk lembut punggung pasanganmu secara berirama untuk memberikan rasa tenang dan relaksasi!", false},
	{581, "DARE", "ACTS_OF_SERVICE", "BOTH", "Bantuan", "Tuliskan kupon: 'Voucher Cuci Motor / Mobil / Bantu Tugas Pasangan' yang bisa ditukar kapan saja!", false},
	{582, "DARE", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Tanyakan menu sarapan yang diinginkan pasangan untuk besok pagi dan catat baik-baik!", false},
	{583, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Bawakan barang bawaan pasanganmu jika dia sedang memegang sesuatu di tangannya!", false},
	{584, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Rapi", "Kuncir rambut pasanganmu (jika perempuan) atau rapikan rambut depannya dengan jari-jemarimu!", false},
	{585, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Buat rangkuman kalender jadwal janji temu penting pasanganmu minggu ini dan ingatkan hal-hal krusial!", false},
	{586, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Perhatian", "Letakkan bantal di punggung atau kepala pasangan agar posisi duduknya menjadi lebih nyaman!", false},
	{587, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pijat", "Pijat pelan pangkal lengan dan bahu pasangan sambil tanyakan apakah tekanan pijatannya sudah pas!", false},
	{588, "DARE", "ACTS_OF_SERVICE", "BOTH", "Pelayanan", "Ucapkan dengan tegas: 'Mulai sekarang, kalau kamu butuh bantuan apapun jangan ragu bilang ke aku ya'!", false},
	{589, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Makanan", "Potongkan buah atau kupaskan camilan untuk pasanganmu sampai siap langsung disantap!", false},
	{590, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Rapi", "Cek dan bersihkan debu atau helaian rambut yang menempel di baju pasanganmu!", false},
	{591, "DARE", "ACTS_OF_SERVICE", "BOTH", "Bantuan", "Tawarkan diri untuk mengantar/menemani pasangan mengurus keperluannya di luar rumah akhir pekan ini!", false},
	{592, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Kirimkan pesan suara bernada alarm lembut: 'Bangun yuk sayang, hari yang hebat sudah menunggumu!' untuk diputar besok pagi!", false},
	{593, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pelayanan", "Tundukkan badan sedikit dan tanyakan: 'Tuan Putri / Pangeran, ada lagi yang bisa saya bantu layani?'!", false},
	{594, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Pijat", "Kecup tangan pasangan yang baru saja kamu pijat sebagai tanda penghormatan atas perjuangannya!", false},
	{595, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Kirimkan kupon 'Voucher Bebas Curhat Tanpa Dihakimi Selama 1 Jam Penuh Kapan Saja' via chat!", false},
	{596, "DARE", "ACTS_OF_SERVICE", "BOTH", "Perhatian", "Ketikkan doa perlindungan khusus untuk keselamatan perjalanan pasanganmu saat beraktivitas besok!", false},
	{597, "DARE", "ACTS_OF_SERVICE", "OFFLINE", "Makanan", "Ambilkan sendok dan tisu makan untuk pasanganmu saat kalian hendak menikmati hidangan!", false},
	{598, "DARE", "ACTS_OF_SERVICE", "ONLINE", "LDR", "Cari informasi nomor kontak darurat atau layanan penting di kota tempat tinggal pasangan dan simpan di catatanmu!", false},
	{599, "DARE", "ACTS_OF_SERVICE", "BOTH", "Bantuan", "Tawarkan diri untuk membantu mencarikan barang atau solusi yang selama seminggu ini sedang dibingungkan pasangan!", false},
	{600, "DARE", "ACTS_OF_SERVICE", "BOTH", "Komitmen", "Katakan: 'Aku ingin selalu menjadi orang pertama yang ada di sampingmu untuk meringankan segala beban hidupmu'!", false},
}
