package deck

import "ulartangga/models"

// DefaultTruths berisi 75 pertanyaan Truth (Kejujuran, Deeptalk, Romantis, & Intim)
var DefaultTruths = []models.QuestionCard{
	{1, "TRUTH", "Deep Talk", "Apa hal pertama yang kamu pikirkan waktu pertama kali kita ketemu atau kenalan?", false},
	{2, "TRUTH", "Memori", "Momen apa selama kita bersama/LDR yang paling bikin kamu kangen berat dan gak bisa tidur?", false},
	{3, "TRUTH", "Romantis", "Apa hal kecil dariku yang paling sering bikin kamu diam-diam tersenyum sendiri?", false},
	{4, "TRUTH", "Deep Talk", "Kapan terakhir kali kamu merasa cemburu, tapi kamu memilih untuk memendamnya sendiri?", false},
	{5, "TRUTH", "Romantis", "Sebutkan 3 sifat atau kebiasaan dariku yang paling bikin kamu merasa nyaman dan aman!", false},
	{6, "TRUTH", "Deep Talk", "Menurutmu, apa tantangan terbesar dalam hubungan kita saat ini dan bagaimana cara kita melaluinya?", false},
	{7, "TRUTH", "Konyol", "Hal konyol atau memalukan apa yang pernah kamu lakuin demi menarik perhatianku waktu awal kenal?", false},
	{8, "TRUTH", "Romantis", "Lagu apa yang setiap kali kamu dengar, otomatis langsung membuatmu mengingat diriku?", false},
	{9, "TRUTH", "Deep Talk", "Pernahkah kamu merasa overthinking tentang masa depan hubungan kita? Apa yang kamu cemaskan?", false},
	{10, "TRUTH", "Memori", "Kalau kita bisa mengulang kembali satu hari terindah dalam hubungan kita, hari mana yang kamu pilih?", false},
	{11, "TRUTH", "Romantis", "Apa panggilan sayang atau kalimat gombalan dariku yang paling bikin kamu salting brutal?", false},
	{12, "TRUTH", "Konyol", "Pernah gak kamu pura-pura sudah tidur atau pura-pura sibuk padahal masih asik scroll sosmed?", false},
	{13, "TRUTH", "Romantis", "Outfit atau gaya penampilan seperti apa dariku yang menurutmu paling memikat hati?", false},
	{14, "TRUTH", "Deep Talk", "Apa ketakutan terbesarmu saat sedang tidak saling memberi kabar lebih dari setengah hari?", false},
	{15, "TRUTH", "Memori", "Kapan momen pertama kalinya kamu yakin dalam hati: 'Kayaknya dia memang orang yang tepat buat aku'?", false},
	{16, "TRUTH", "Deep Talk", "Hal apa dari dirimu sendiri yang paling ingin kamu perbaiki demi kebaikan hubungan kita berdua?", false},
	{17, "TRUTH", "Romantis", "Jika kita punya waktu 24 jam bebas tanpa gadget dan pekerjaan, apa saja hal yang ingin kamu lakukan bersamaku?", false},
	{18, "TRUTH", "Spicy", "Bagian wajah atau tubuhku mana yang paling sering membuatmu gemas dan ingin kamu peluk/cubit?", false},
	{19, "TRUTH", "Konyol", "Siapa di antara kita yang menurutmu paling gengsian dan paling sulit buat minta maaf duluan?", false},
	{20, "TRUTH", "Deep Talk", "Apa harapan atau impian terbesar yang ingin kamu wujudkan bersama denganku 3 tahun ke depan?", false},
	{21, "TRUTH", "Deep Talk", "Pernah gak kamu menangis diam-diam sendirian karena merindukan kehadiranku? Ceritakan momennya!", false},
	{22, "TRUTH", "Romantis", "Hal apa yang aku lakukan yang tanpa kusadari selalu berhasil meluluhkan hatimu saat kamu lagi bad mood?", false},
	{23, "TRUTH", "Konyol", "Kebiasaan aneh atau random apa dariku yang menurutmu lucu banget tapi gak kamu temuin di orang lain?", false},
	{24, "TRUTH", "Memori", "Ceritakan obrolan larut malam (late night talk) kita yang paling berkesan dan paling menyentuh hatimu!", false},
	{25, "TRUTH", "Spicy", "Wangi parfum, aroma tubuh, atau suasana seperti apa dariku yang paling bikin kamu betah berlama-lama dekat denganku?", false},
	{26, "TRUTH", "Deep Talk", "Apa pujian paling tulus dariku yang pernah kamu terima dan masih kamu ingat sampai hari ini?", false},
	{27, "TRUTH", "Romantis", "Jika kamu harus mendeskripsikan cintamu padaku hanya dalam 3 kata, 3 kata apa yang kamu pilih?", false},
	{28, "TRUTH", "Konyol", "Pernah gak kamu nge-stalk akun sosmedku sampai postingan bertahun-tahun lalu waktu awal kita pdkt?", false},
	{29, "TRUTH", "Deep Talk", "Hal apa yang paling kamu syukuri dari takdir yang mempertemukan kita berdua?", false},
	{30, "TRUTH", "Memori", "Foto atau video kita berdua yang mana yang menjadi favoritmu sepanjang masa di galeri HP-mu?", false},
	{31, "TRUTH", "Romantis", "Apa arti 'rumah' bagimu, dan bagaimana diriku bisa menjadi tempat pulang ternyaman untukmu?", false},
	{32, "TRUTH", "Deep Talk", "Pernahkah kamu merasa insecure saat bersamaku? Apa yang membuatmu merasa demikian?", false},
	{33, "TRUTH", "Konyol", "Ceritakan kebohongan kecil dan polos yang pernah kamu ucapkan ke aku agar aku tidak ngambek!", false},
	{34, "TRUTH", "Romantis", "Kapan momen di mana kamu merasa paling dilindungi dan disayangi olehku?", false},
	{35, "TRUTH", "Deep Talk", "Bagaimana caramu menenangkan diri ketika kita sedang berbeda pendapat atau suasana hati sedang dingin?", false},
	{36, "TRUTH", "Memori", "Makanan atau tempat kencan sederhana mana yang punya kenangan paling manis buat kita berdua?", false},
	{37, "TRUTH", "Spicy", "Jika kita berduaan di ruangan yang tenang dan dingin, sentuhan apa yang paling kamu nantikan dariku?", false},
	{38, "TRUTH", "Konyol", "Hal apa yang paling sering bikin kita berdua tertawa lepas sampai sakit perut?", false},
	{39, "TRUTH", "Deep Talk", "Seberapa besar kehadiran diriku mengubah caramu memandang masa depan hidupmu?", false},
	{40, "TRUTH", "Romantis", "Apa hal yang paling kamu rindukan saat kita terpisah jarak dan hanya bisa bertukar pesan teks?", false},
	{41, "TRUTH", "Memori", "Momen 'first kiss' atau sentuhan fisik pertama kita, apa yang ada di kepalamu saat itu?", false},
	{42, "TRUTH", "Deep Talk", "Apakah ada rahasia atau impian masa kecilmu yang belum pernah kamu ceritakan ke siapapun kecuali aku?", false},
	{43, "TRUTH", "Romantis", "Jika aku harus pergi merantau jauh untuk beberapa waktu, janji apa yang ingin selalu kita pegang berdua?", false},
	{44, "TRUTH", "Konyol", "Siapa yang paling boros dan paling gampang tergiur jajan online saat kita lagi bareng?", false},
	{45, "TRUTH", "Deep Talk", "Pernahkah kamu merasa takut kehilangan diriku lebih dari takut kehilangan hal-hal lainnya?", false},
	{46, "TRUTH", "Romantis", "Bagian mana dari tatapan mataku yang paling sering membuat detak jantungmu berdegup lebih kencang?", false},
	{47, "TRUTH", "Konyol", "Tebak, apa hal dariku yang paling sering membuatmu geregetan atau pengen gigit?", false},
	{48, "TRUTH", "Memori", "Apa kado atau kejutan dariku yang paling menyentuh dan paling berharga buat hatimu?", false},
	{49, "TRUTH", "Deep Talk", "Jika hari ini adalah hari terakhir sebelum kita menua, apa yang ingin kamu sampaikan padaku?", false},
	{50, "TRUTH", "Romantis", "Kenapa kamu memilih untuk tetap bertahan dan mencintaiku sampai detik ini?", false},
	{57, "TRUTH", "Deep Talk", "Siapa yang paling suka bikin janji 'nanti telpon' tapi kadang PHP alias ternyata gak jadi?", false},

	// 25 KARTU TRUTH INTIM & ROMANTIS (ID 101-125)
	{101, "TRUTH", "Intim", "Apa yang kamu rasakan di dalam hatimu saat jemari tangan kita saling menggenggam erat waktu berjalan berdua?", false},
	{102, "TRUTH", "Intim", "Bentuk pelukan seperti apa dariku yang paling membuatmu merasa damai, tenang, dan terlindungi dari lelahnya dunia?", false},
	{103, "TRUTH", "Intim", "Kapan momen di mana kamu merasa sangat membutuhkan genggaman tanganku tanpa perlu mengucapkannya lewat kata-kata?", false},
	{104, "TRUTH", "Intim", "Sentuhan fisik lembut apa dariku (mengelus rambut, memegang pipi, atau menggandeng tangan) yang paling bikin kamu meleleh?", false},
	{105, "TRUTH", "Intim", "Jika kita sedang duduk bersandar berdua dalam hening tanpa gadget, apa yang paling ingin kamu bisikkan padaku?", false},
	{106, "TRUTH", "Intim", "Ceritakan apa yang terlintas di pikiranmu saat pertama kali tangan kita bersentuhan tanpa sengaja di awal pertemuan!", false},
	{107, "TRUTH", "Intim", "Saat kamu sedang sedih atau lelah, apakah kamu lebih memilih untuk didekap erat dalam diam atau diajak bercerita?", false},
	{108, "TRUTH", "Intim", "Bagian mana dari kebiasaan fisik kita berdua saat bersama yang paling membuatmu selalu rindu saat pulang?", false},
	{109, "TRUTH", "Intim", "Pernahkah kamu diam-diam memperhatikan wajahku saat aku sedang tertidur lelap? Apa yang kamu rasakan saat itu?", false},
	{110, "TRUTH", "Intim", "Apa arti sentuhan tangan pasangan bagimu dalam menguatkan komitmen dan rasa percaya di antara kita?", false},
	{111, "TRUTH", "Intim", "Jika kita sedang jalan berdua di tempat ramai, gestur mesra apa yang paling membuatmu merasa bangga menjadi pasanganku?", false},
	{112, "TRUTH", "Intim", "Seberapa sering kamu mendambakan pelukan hangat dariku saat seharian menghadapi hari yang berat?", false},
	{113, "TRUTH", "Intim", "Bagaimana perasaanmu saat aku menatap matamu dari jarak dekat tanpa sepatah kata pun terucap?", false},
	{114, "TRUTH", "Intim", "Apa satu hal tentang keintiman emosional di antara kita yang menurutmu paling istimewa dibanding siapapun?", false},
	{115, "TRUTH", "Intim", "Ketika tangan kita saling bertaut, pesan atau rasa apa yang paling kuat tersampaikan ke dalam jiwamu?", false},
	{116, "TRUTH", "Intim", "Pernahkah kamu merasa detak jantungmu berdegup sangat kencang hanya karena aku mendekatkan wajahku padamu?", false},
	{117, "TRUTH", "Intim", "Apa panggilan sayang atau bisikan paling mesra dariku yang selalu terngiang-ngiang manis di kepalamu?", false},
	{118, "TRUTH", "Intim", "Apakah kamu merasa aman dan bebas menjadi diri sendiri seutuhnya saat berada di dalam dekapanku? Mengapa?", false},
	{119, "TRUTH", "Intim", "Apa satu hal tentang kemesraan atau sentuhan fisik yang dulu membuatmu malu/canggung, tapi kini sangat kamu sukai?", false},
	{120, "TRUTH", "Intim", "Momen mesra apa di antara kita yang menurutmu paling berharga dan tak akan pernah bisa kamu lupakan seumur hidup?", false},
	{121, "TRUTH", "Intim", "Bagian mana dari caraku memperlakukan fisik dan perasaanmu yang paling membuatmu merasa sangat dihargai?", false},
	{122, "TRUTH", "Intim", "Jika kamu bisa meminta satu sentuhan kasih sayang dariku setiap hari sebelum tidur, sentuhan apa yang paling kamu pilih?", false},
	{123, "TRUTH", "Intim", "Apa konsep kencan berdua yang paling tenang, intim, dan bebas dari gangguan orang lain yang ingin kita wujudkan?", false},
	{124, "TRUTH", "Intim", "Kapan kamu merasa tatapan mataku benar-benar menyampaikan rasa sayang yang begitu dalam tanpa perlu sepatah kata pun?", false},
	{125, "TRUTH", "Intim", "Apa satu kalimat tulus dari lubuk hatimu yang paling ingin kamu bisikkan padaku saat ini juga?", false},
}

// DefaultDares berisi 75 tantangan aksi Dare (Aksi Romantis, Konyol, Spicy, & Gestur Intim)
var DefaultDares = []models.QuestionCard{
	{51, "DARE", "Konyol", "Tatap mata pasanganku lekat-lekat selama 30 detik tanpa boleh tersenyum atau tertawa!", false},
	{52, "DARE", "Romantis", "Kirim voice note 15 detik nyanyiin reff lagu cinta paling romantis khusus buat aku sekarang juga!", false},
	{53, "DARE", "Konyol", "Tirukan suara kucing manja yang lagi minta makan sambil nengok ke kamera/pasangan!", false},
	{54, "DARE", "Romantis", "Gombalin aku dengan menggunakan 3 kata acak: 'Kulkas', 'Ular Tangga', dan 'Masa Depan'!", false},
	{55, "DARE", "Konyol", "Kirim/tunjukkan foto selfie dengan ekspresi wajah paling jelek & konyol di galeri HP kamu!", false},
	{56, "DARE", "Romantis", "Berikan 5 pujian tulus tentang fisik dan kepribadianku berturut-turut tanpa jeda berpikir!", false},
	{57, "DARE", "Spicy", "Bisikkan kata-kata paling menggoda atau manis ke telinga pasangan / speaker HP selama 10 detik!", false},
	{58, "DARE", "Konyol", "Joget lucu tanpa musik selama 20 detik di depan pasangan / kamera dengan penuh percaya diri!", false},
	{59, "DARE", "Romantis", "Tulis pesan 1 paragraf berisi alasan kenapa kamu bersyukur punya aku, lalu kirim ke chat kita sekarang!", false},
	{60, "DARE", "Konyol", "Tahan napas sambil bilang 'Aku sayang banget sama kamu dan gak mau kehilangan kamu!' sebanyak 3 kali!", false},
	{61, "DARE", "Romantis", "Pasang foto kita berdua jadi wallpaper HP kamu sampai sesi permainan ini selesai!", false},
	{62, "DARE", "Konyol", "Peragakan cara aku berjalan atau cara aku waktu lagi ngambek dengan akting terbaikmu!", false},
	{63, "DARE", "Spicy", "Tatap kamera/pasangan dengan tatapan paling memikat selama 15 detik tanpa berkedip!", false},
	{64, "DARE", "Romantis", "Berikan kecupan manis bertubi-tubi (jika dekat) atau kirim flying kiss paling heboh ke kamera!", false},
	{65, "DARE", "Konyol", "Buat pantun cinta lucu 4 baris yang rima akhirnya berakhiran namaku!", false},
	{66, "DARE", "Deep Talk", "Ucapkan satu permintaan maaf tulus untuk hal kecil di masa lalu yang mungkin pernah menyakiti hatiku!", false},
	{67, "DARE", "Romantis", "Pegang kedua tanganku erat-erat, tatap mataku, dan katakan: 'Masa depanku adalah bersamamu'!", false},
	{68, "DARE", "Spicy", "Kecup kening pasanganku dengan sangat lembut dan tahan selama 5 detik penuh penghayatan!", false},
	{69, "DARE", "Konyol", "Tirukan ekspresi wajah emoji yang dipilihkan oleh pasanganmu!", false},
	{70, "DARE", "Romantis", "Ceritakan kembali detik-detik pertama kali kamu menembakku atau menyatakan perasaanmu padaku!", false},
	{71, "DARE", "Spicy", "Pijat lembut pundak atau leher pasanganmu selama 1 menit penuh perhatian!", false},
	{72, "DARE", "Konyol", "Bicara dengan logat bayi (baby talk) selama 2 putaran ke depan!", false},
	{73, "DARE", "Romantis", "Sebutkan 3 hal dari diriku yang membuatmu jatuh cinta setiap hari berulang kali!", false},
	{74, "DARE", "Konyol", "Kirimkan stiker chat WA paling cringe dan aneh yang ada di koleksimu ke pasangan!", false},
	{75, "DARE", "Spicy", "Gigit manja jari telunjuk pasanganmu (atau cubit gemas pipinya jika LDR)!", false},
	{76, "DARE", "Romantis", "Ucapkan kalimat cinta dalam 3 bahasa asing yang berbeda!", false},
	{77, "DARE", "Konyol", "Bikin suara ketawa paling aneh dan kencang yang bisa kamu buat sekarang juga!", false},
	{78, "DARE", "Spicy", "Peluk erat pasanganmu dari belakang (backhug) selama 30 detik tanpa melepaskannya!", false},
	{79, "DARE", "Romantis", "Tulis nama panggilanku di status WhatsApp atau bio sosmedmu selama 1 jam!", false},
	{80, "DARE", "Konyol", "Makan camilan/minum air dengan gaya orang yang lagi mabuk kepayang!", false},
	{81, "DARE", "Deep Talk", "Tatap mataku dan sebutkan satu janji setia yang akan selalu kamu jaga untuk hubungan kita!", false},
	{82, "DARE", "Romantis", "Bikin video pendek 10 detik mengucapkan selamat malam paling manis untuk disimpan!", false},
	{83, "DARE", "Spicy", "Bisikkan gombalan maut tepat di samping telingaku sampai bulu kudukku merinding!", false},
	{84, "DARE", "Konyol", "Gaya catwalk ala supermodel di depan pasanganmu selama 15 detik!", false},
	{85, "DARE", "Romantis", "Sebutkan 5 panggilan sayang unik yang hanya boleh kita berdua gunakan!", false},
	{86, "DARE", "Spicy", "Beri kecupan hangat di pipi kanan, pipi kiri, dan hidung pasanganku secara bergantian!", false},
	{87, "DARE", "Konyol", "Pura-pura jadi sales promosi yang sedang mempromosikan kehebatan pasangannya!", false},
	{88, "DARE", "Romantis", "Tutup mata, raba wajah pasanganmu, dan tebak bagian mana yang sedang kamu sentuh!", false},
	{89, "DARE", "Spicy", "Rangkul pinggang pasanganmu dan tatap matanya selama 20 detik tanpa berbicara!", false},
	{90, "DARE", "Konyol", "Ngedip genit 10 kali berturut-turut ke arah pasangan secepat mungkin!", false},
	{91, "DARE", "Romantis", "Nyanyikan lagu ulang tahun atau lagu cinta dengan mengganti liriknya dengan namaku!", false},
	{92, "DARE", "Deep Talk", "Ungkapkan satu kekaguman terbesarmu atas perjuangan hidupku yang selama ini kamu saksikan!", false},
	{93, "DARE", "Spicy", "Elus lembut rambut pasanganmu sampai dia merasa nyaman dan mengantuk!", false},
	{94, "DARE", "Konyol", "Tunjukkan riwayat pencarian (search history) terakhir di Google atau YouTube HP-mu!", false},
	{95, "DARE", "Romantis", "Gendong (atau rangkul erat) pasanganmu selama 15 detik sambil berputar perlahan!", false},
	{96, "DARE", "Spicy", "Kecup punggung tangan pasanganku seperti seorang pangeran/putri yang sedang berjanji setia!", false},
	{97, "DARE", "Konyol", "Bikin ekspresi wajah paling salting yang pernah ada di dunia!", false},
	{98, "DARE", "Romantis", "Tuliskan 1 doa terbaikmu untuk hubungan kita di secarik kertas/notes HP dan bacakan!", false},
	{99, "DARE", "Romantis", "Berlutut dengan satu kaki (seperti melamar) dan sampaikan kata-kata manis dari hatimu!", false},
	{100, "DARE", "Romantis", "Letakkan tanganmu di dadamu, tatap pasanganmu, dan ucapkan 'Terima kasih sudah mencintaiku apa adanya'!", false},
	{21, "DARE", "Konyol", "Impersonate kata-kata yang sering aku ucapin waktu videocall pakai gaya suaraku!", false},

	// 25 KARTU DARE INTIM & GANDENGAN TANGAN (ID 126-150)
	{126, "DARE", "Intim", "Gandeng tangan pasanganmu erat-erat (jemari saling mengunci) dan jangan lepaskan sampai 2 putaran ke depan!", false},
	{127, "DARE", "Intim", "Genggam kedua tangan pasanganmu, cium punggung tangannya dengan lembut, dan ucapkan terima kasih karena telah memilihmu!", false},
	{128, "DARE", "Intim", "Tautkan jemari tanganmu dengan jemari pasangan sambil tatap matanya selama 20 detik tanpa boleh berkedip!", false},
	{129, "DARE", "Intim", "Letakkan telapak tanganmu di dada pasanganmu (atau di dadamu jika LDR), rasakan detak jantungnya dan katakan satu hal yang paling kamu cintai darinya!", false},
	{130, "DARE", "Intim", "Elus lembut rambut atau kepala pasanganmu dengan penuh kasih sayang selama 30 detik sambil berikan satu pujian tulus!", false},
	{131, "DARE", "Intim", "Peluk erat pasanganmu (bisa pelukan hangat atau backhug) selama 45 detik penuh kehangatan tanpa dilepas!", false},
	{132, "DARE", "Intim", "Belai lembut pipi pasanganmu lalu berikan kecupan manis di keningnya (jika LDR: tiup kecupan hangat ke kamera dengan tatapan paling teduh)!", false},
	{133, "DARE", "Intim", "Pijat lembut telapak tangan dan jari-jemari pasanganmu satu per satu dengan penuh perhatian selama 1 menit!", false},
	{134, "DARE", "Intim", "Lakukan 'Eskimo Kiss' (saling menempelkan dan menggesekkan ujung hidung berdua secara lembut dan menggemaskan) selama 10 detik!", false},
	{135, "DARE", "Intim", "Rebahkan kepalamu di bahu atau pangkuan pasanganmu selama 1 menit sambil mendengarkan detak suaranya!", false},
	{136, "DARE", "Intim", "Bisikkan dengan sangat pelan di dekat telinga pasanganmu satu hal rahasia tentang dirimu yang belum pernah kamu akui sebelumnya!", false},
	{137, "DARE", "Intim", "Ambil kedua tangan pasanganmu, genggam hangat di dadamu, dan tatap matanya sambil bilang: 'Aku bangga banget punya kamu di hidupku'!", false},
	{138, "DARE", "Intim", "Tarik pasanganmu perlahan ke dalam pelukan pelan (slow hug) tanpa suara selama 30 detik penuh kenyamanan!", false},
	{139, "DARE", "Intim", "Cium kedua pipi pasanganmu (kanan dan kiri) secara berurutan lalu cubit pipinya dengan gemas!", false},
	{140, "DARE", "Intim", "Tuliskan satu kata cinta dengan ujung jarimu di telapak tangan pasanganmu, dan biarkan pasanganmu menebak kata apa itu!", false},
	{141, "DARE", "Intim", "Berdansa pelan berdua (slow dance) tanpa musik selama 30 detik sambil saling berpegangan tangan erat!", false},
	{142, "DARE", "Intim", "Sentuh tengkuk leher atau pundak pasanganmu dengan lembut sambil katakan: 'Kamu udah berusaha hebat banget hari ini'!", false},
	{143, "DARE", "Intim", "Gandeng tangan pasanganmu dan tempelkan di pipimu sendiri sambil tersenyum manis menatap matanya!", false},
	{144, "DARE", "Intim", "Sandarkan dagumu di bahu pasanganmu sambil tersenyum menatap layar/kaca bersama selama 20 detik!", false},
	{145, "DARE", "Intim", "Berikan kecupan lembut di setiap ujung jari tangan pasanganmu satu per satu dengan penuh kasih!", false},
	{146, "DARE", "Intim", "Bisikkan dengan nada menggoda ke telinga pasanganmu satu hal yang paling ingin kamu lakukan saat kita berduaan nanti!", false},
	{147, "DARE", "Intim", "Pegang kedua pipi pasanganmu dengan kedua tanganmu, tatap matanya lekat-lekat, lalu katakan: 'Jangan pernah ragu sama perasaanku ya'!", false},
	{148, "DARE", "Intim", "Usap pelan punggung pasanganmu dengan pola lingkaran lembut untuk membuatnya rileks dan merasa tenang!", false},
	{149, "DARE", "Intim", "Genggam satu tangan pasanganmu dan masukkan ke dalam saku jaket/baju bersama (atau dekap erat di pangkuan) selama 1 putaran!", false},
	{150, "DARE", "Intim", "Kuncikan tatapan mata kalian berdua dari jarak dekat (kurang dari 15 cm) selama 20 detik tanpa boleh tertawa atau mengalihkan pandangan!", false},
}
