package deck

import "ulartangga/models"

// PhysicalTouchDeck berisi 100 kartu bahasa cinta Sentuhan Fisik & Keintiman Romantis (50 Truth + 50 Dare)
// Dibagi ke dalam mode ONLINE (Video Call / LDR), OFFLINE (Ketemu Langsung), dan BOTH (Bisa Keduanya)
var PhysicalTouchDeck = []models.QuestionCard{
	// 50 TRUTH - PHYSICAL TOUCH (ID 601 - 650)
	{601, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Intim", "Apa yang kamu rasakan di dalam hatimu saat jemari tangan kita saling menggenggam erat waktu berjalan berdua?", false},
	{602, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Pelukan", "Bentuk pelukan seperti apa dariku yang paling membuatmu merasa damai, tenang, dan terlindungi dari lelahnya dunia?", false},
	{603, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Genggaman", "Kapan momen di mana kamu merasa sangat membutuhkan genggaman tanganku tanpa perlu mengucapkannya lewat kata-kata?", false},
	{604, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Sentuhan", "Sentuhan fisik lembut apa dariku (mengelus rambut, memegang pipi, atau menggandeng tangan) yang paling bikin kamu meleleh?", false},
	{605, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Keintiman", "Jika kita sedang duduk bersandar berdua dalam hening tanpa gadget, sentuhan apa yang paling membuatmu merasa aman?", false},
	{606, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Memori", "Ceritakan apa yang terlintas di pikiranmu saat pertama kali tangan kita bersentuhan tanpa sengaja di awal pertemuan!", false},
	{607, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Pelukan", "Saat kamu sedang sedih atau lelah, apakah kamu lebih memilih untuk didekap erat dalam diam atau diajak bercerita?", false},
	{608, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Sentuhan", "Bagian mana dari kebiasaan fisik kita berdua saat bersama yang paling membuatmu selalu rindu saat pulang?", false},
	{609, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Keintiman", "Pernahkah kamu diam-diam memperhatikan wajahku saat aku sedang tertidur lelap di dekatmu? Apa rasanya?", false},
	{610, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Genggaman", "Apa arti sentuhan tangan pasangan bagimu dalam menguatkan komitmen dan rasa percaya di antara kita?", false},
	{611, "TRUTH", "PHYSICAL_TOUCH", "OFFLINE", "Romantis", "Jika kita sedang jalan berdua di tempat ramai, gestur mesra apa yang paling membuatmu merasa bangga menjadi pasanganku?", false},
	{612, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Pelukan", "Seberapa sering kamu mendambakan pelukan hangat dariku saat seharian menghadapi hari yang berat?", false},
	{613, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Tatap Mata", "Bagaimana perasaanmu saat aku menatap matamu dari jarak sangat dekat tanpa sepatah kata pun terucap?", false},
	{614, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Keintiman", "Apa satu hal tentang keintiman emosional dan fisik di antara kita yang menurutmu paling istimewa dibanding siapapun?", false},
	{615, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Genggaman", "Ketika tangan kita saling bertaut erat, pesan atau rasa apa yang paling kuat tersampaikan ke dalam jiwamu?", false},
	{616, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Debaran", "Pernahkah kamu merasa detak jantungmu berdegup sangat kencang hanya karena aku mendekatkan wajahku padamu?", false},
	{617, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Bisikan", "Apa bisikan paling mesra dariku saat berada di dekatmu yang selalu terngiang-ngiang manis di kepalamu?", false},
	{618, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Keamanan", "Apakah kamu merasa aman dan bebas menjadi diri sendiri seutuhnya saat berada di dalam dekapanku? Mengapa?", false},
	{619, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Canggung", "Apa satu hal tentang kemesraan atau sentuhan fisik yang dulu membuatmu malu/canggung, tapi kini sangat kamu sukai?", false},
	{620, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Memori", "Momen mesra apa di antara kita yang menurutmu paling berharga dan tak akan pernah bisa kamu lupakan seumur hidup?", false},
	{621, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Sentuhan", "Bagian mana dari caraku memperlakukan fisik dan perasaanmu yang paling membuatmu merasa sangat dihargai?", false},
	{622, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Ritual", "Jika kamu bisa meminta satu sentuhan kasih sayang dariku setiap hari sebelum tidur, sentuhan apa yang paling kamu pilih?", false},
	{623, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Keintiman", "Apa konsep kencan berdua yang paling tenang, intim, dan bebas dari gangguan orang lain yang ingin kita wujudkan?", false},
	{624, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Tatap Mata", "Kapan kamu merasa tatapan mataku benar-benar menyampaikan rasa sayang yang begitu dalam tanpa kata-kata?", false},
	{625, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Ciuman", "Di mana ciuman manis dariku (kening, pipi, atau tangan) yang paling terasa tulus dan menyejukkan hatimu?", false},
	{626, "TRUTH", "PHYSICAL_TOUCH", "OFFLINE", "Sandaran", "Apakah menyandarkan kepala di bahu atau dadaku adalah tempat peristirahatan ternyamanmu di dunia saat kita bersama?", false},
	{627, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Sensasi", "Pernahkah elusan lembut di rambut atau lehermu membuat rasa kantuk dan ketenanganmu datang seketika?", false},
	{628, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Kehangatan", "Bagaimana caramu menyampaikan bahwa kamu sedang butuh dipeluk tanpa harus merasa malu atau gengsi?", false},
	{629, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Memori", "Apakah kamu masih ingat sensasi hangat saat pertama kali jari-jari tangan kita saling mengunci di kencan awal?", false},
	{630, "TRUTH", "PHYSICAL_TOUCH", "OFFLINE", "Backhug", "Apa yang terlintas di benakmu saat aku memelukmu tiba-tiba dari belakang (backhug) saat kamu sedang sibuk?", false},
	{631, "TRUTH", "PHYSICAL_TOUCH", "OFFLINE", "Sentuhan", "Jika cuaca sedang dingin dan hujan deras, posisi duduk berdua seperti apa yang paling kamu impikan bersamaku?", false},
	{632, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Spicy", "Bagian mana dari tubuh atau aromaku yang paling sering membuatmu gemas ingin memeluk lebih erat?", false},
	{633, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Keintiman", "Seberapa besar pengaruh sentuhan fisik pasangan dalam meredakan rasa cemas atau rasa takutmu?", false},
	{634, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Tatap Mata", "Momen tatap-tatapan mata paling intens mana yang pernah membuatmu sampai tersipu merah dan menutup wajah?", false},
	{635, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Sentuhan", "Apakah kamu lebih menyukai usapan lembut di punggung atau belaian di telapak tangan saat kita berbincang?", false},
	{636, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Keintiman", "Apa arti pelukan perpisahan saat kita harus kembali ke tempat masing-masing bagimu?", false},
	{637, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Romantis", "Kapan kamu merasa debaran fisik kita berdua menyatu menjadi satu ritme yang begitu tenang?", false},
	{638, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Cinta", "Kenapa berada dalam dekapanmu selalu terasa seperti pulang ke rumah ternyaman di muka bumi?", false},
	{639, "TRUTH", "PHYSICAL_TOUCH", "ONLINE", "LDR", "Bagian mana dari tubuhmu yang paling merindukan pelukan hangat saat kita terpisah jarak dan hanya bisa saling menatap di layar?", false},
	{640, "TRUTH", "PHYSICAL_TOUCH", "ONLINE", "LDR", "Apakah kamu pernah memeluk guling atau bantal sambil membayangkan itu adalah aku saat kamu sangat merindukan kehadiranku?", false},
	{641, "TRUTH", "PHYSICAL_TOUCH", "ONLINE", "LDR", "Ketika aku meniupkan ciuman ke kamera di akhir video call, apakah kamu merasakan kehangatannya sampai ke hatimu?", false},
	{642, "TRUTH", "PHYSICAL_TOUCH", "OFFLINE", "Kemesraan", "Gestur fisik kecil apa (seperti mencubit hidung, merapikan poni) yang paling sering kulakukan saat kita berdekatan?", false},
	{643, "TRUTH", "PHYSICAL_TOUCH", "ONLINE", "LDR", "Apa hal pertama yang ingin kamu sentuh (tangan, pipi, atau langsung mendekap tubuhku) saat hari pertama kita bertemu nanti?", false},
	{644, "TRUTH", "PHYSICAL_TOUCH", "OFFLINE", "Sandaran", "Bagaimana rasanya ketika tangan kita saling bertaut di dalam saku jaket saat berjalan di udara malam yang dingin?", false},
	{645, "TRUTH", "PHYSICAL_TOUCH", "ONLINE", "LDR", "Seberapa sering kamu menyentuh foto kita berdua di layar HP saat sedang rindu berat di malam hari?", false},
	{646, "TRUTH", "PHYSICAL_TOUCH", "OFFLINE", "Sensasi", "Pernahkah ciuman di kening membuat air matamu menetes karena merasa begitu dimuliakan dan disayangi?", false},
	{647, "TRUTH", "PHYSICAL_TOUCH", "ONLINE", "LDR", "Apa gestur di video call (misal: meletakkan tangan di dada, senyum dekat kamera) yang paling bisa menggantikan rasa rindu fisikmu?", false},
	{648, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Keamanan", "Kenapa sentuhan fisik dari orang yang kita cintai memiliki kekuatan menyembuhkan luka batin lebih cepat dari apapun?", false},
	{649, "TRUTH", "PHYSICAL_TOUCH", "OFFLINE", "Intim", "Kapan momen di mana kamu merasa pelukan kita berdua berlangsung begitu lama dan tak ingin berakhir?", false},
	{650, "TRUTH", "PHYSICAL_TOUCH", "BOTH", "Komitmen", "Apakah kamu percaya bahwa keintiman fisik yang dilandasi rasa saling menghormati adalah pondasi kebahagiaan hubungan jangka panjang?", false},

	// 50 DARE - PHYSICAL TOUCH (ID 651 - 700)
	// Dibagi jelas: OFFLINE (Sentuhan langsung), ONLINE (Adaptasi LDR Video Call yang intim & kreatif)
	{651, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Genggaman", "Gandeng tangan pasanganmu erat-erat (jemari saling mengunci) dan jangan lepaskan sampai 2 putaran ke depan!", false},
	{652, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Virtual Touch", "Tempelkan telapak tanganmu ke layar kamera HP tepat di posisi telapak tangan pasanganmu selama 20 detik!", false},
	{653, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Cium Tangan", "Genggam kedua tangan pasanganmu, cium punggung tangannya dengan lembut, dan ucapkan terima kasih karena telah memilihmu!", false},
	{654, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Flying Kiss", "Kecup punggung tanganmu sendiri di depan kamera, lalu tiupkan kecupan hangat itu lurus ke lensa video call untuk pasanganmu!", false},
	{655, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Tatap Mata", "Tautkan jemari tanganmu dengan jemari pasangan sambil tatap matanya selama 20 detik tanpa boleh berkedip!", false},
	{656, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Eye Lock", "Dekatkan wajahmu ke layar video call (jarak 10 cm), kunci tatapan mata dengan pasangan selama 20 detik tanpa mengalihkan pandangan!", false},
	{657, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Detak Jantung", "Letakkan telapak tanganmu di dada pasanganmu, rasakan detak jantungnya dan katakan satu hal yang paling kamu cintai darinya!", false},
	{658, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Detak Jantung", "Letakkan telapak tanganmu di dadamu sendiri, pejamkan mata, dan ucapkan kata sayang seolah pasangan sedang berada di dekapanmu!", false},
	{659, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Elus Rambut", "Elus lembut rambut atau kepala pasanganmu dengan penuh kasih sayang selama 30 detik sambil berikan satu pujian tulus!", false},
	{660, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Self Elus", "Elus lembut kepalamu sendiri di depan kamera sambil tatap pasanganmu dan katakan: 'Anggap ini tanganmu yang lagi ngelus aku ya'!", false},
	{661, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Pelukan", "Peluk erat pasanganmu (bisa pelukan hangat atau backhug) selama 45 detik penuh kehangatan tanpa dilepas!", false},
	{662, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Self Hug", "Peluk dirimu sendiri seerat mungkin (dekap kedua lenganmu) di depan kamera sambil tatap matanya dengan ekspresi rindu yang dalam!", false},
	{663, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Kecupan", "Belai lembut pipi pasanganmu lalu berikan kecupan manis di keningnya dengan penuh penghayatan!", false},
	{664, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Virtual Kiss", "Dekatkan bibirmu ke lensa kamera HP dan berikan kecupan lembut 'Mmuaah' yang terdengar manis di speaker pasangan!", false},
	{665, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Pijat Tangan", "Pijat lembut telapak tangan dan jari-jemari pasanganmu satu per satu dengan penuh perhatian selama 1 menit!", false},
	{666, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Finger Touch", "Sentuh layar video call tepat di area wajah pasanganmu dan gerakkan jarimu seolah sedang membelai pipinya dengan lembut!", false},
	{667, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Eskimo Kiss", "Lakukan 'Eskimo Kiss' (saling menempelkan dan menggesekkan ujung hidung berdua secara lembut dan menggemaskan) selama 10 detik!", false},
	{668, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Nose Touch", "Dekatkan ujung hidungmu ke kamera HP dan buat ekspresi menggemaskan seolah sedang melakukan Eskimo Kiss virtual!", false},
	{669, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Sandaran", "Rebahkan kepalamu di bahu atau pangkuan pasanganmu selama 1 menit sambil mendengarkan detak suaranya!", false},
	{670, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Pillow Hug", "Ambil bantal atau guling di dekatmu, dekap erat di depan kamera dan letakkan dagumu di atasnya sambil tersenyum menatap pasangan!", false},
	{671, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Bisikan", "Bisikkan dengan sangat pelan di dekat telinga pasanganmu satu hal rahasia tentang dirimu yang belum pernah kamu akui sebelumnya!", false},
	{672, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Whisper Mic", "Dekatkan microphone HP tepat ke bibirmu dan bisikkan kalimat mesra dengan suara paling serak dan seksi selama 10 detik!", false},
	{673, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Pegang Dada", "Ambil kedua tangan pasanganmu, genggam hangat di dadamu, dan tatap matanya sambil bilang: 'Aku bangga banget punya kamu'!", false},
	{674, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Heart Shape", "Bentuk simbol hati besar menggunakan kedua tanganmu di dada, lalu dorong ke arah kamera seolah mempersembahkan hatimu!", false},
	{675, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Slow Hug", "Tarik pasanganmu perlahan ke dalam pelukan pelan (slow hug) tanpa suara selama 30 detik penuh kenyamanan!", false},
	{676, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Virtual Caress", "Belaikan tanganmu di udara di depan kamera HP dengan gerakan lembut seirama seakan sedang mengelus pipi pasangan!", false},
	{677, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Pipi", "Cium kedua pipi pasanganmu (kanan dan kiri) secara berurutan lalu cubit pipinya dengan gemas!", false},
	{678, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Cheek Pinch", "Cubit kedua pipimu sendiri di depan kamera dengan pose paling lucu dan manja sampai pasanganmu tersenyum!", false},
	{679, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Tebak Kata", "Tuliskan satu kata cinta dengan ujung jarimu di telapak tangan pasanganmu, dan biarkan pasanganmu menebak kata apa itu!", false},
	{680, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Air Draw", "Tuliskan satu kata cinta dengan jarimu di udara di depan kamera video call, dan minta pasanganmu menebak kata tersebut!", false},
	{681, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Slow Dance", "Berdansa pelan berdua (slow dance) tanpa musik selama 30 detik sambil saling berpegangan tangan erat!", false},
	{682, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Swaying", "Goyangkan tubuhmu perlahan ke kiri dan ke kanan di depan kamera mengikuti irama lagu romantis imajiner berdua!", false},
	{683, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Pundak", "Sentuh tengkuk leher atau pundak pasanganmu dengan lembut sambil katakan: 'Kamu udah berusaha hebat banget hari ini'!", false},
	{684, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Shoulder Tap", "Sentuh kedua pundakmu sendiri sambil tatap kamera dan katakan kalimat penyemangat terhangat untuk pasanganmu!", false},
	{685, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Pipi Tangan", "Gandeng tangan pasanganmu dan tempelkan di pipimu sendiri sambil tersenyum manis menatap matanya!", false},
	{686, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Screen Palm", "Letakkan pipimu di samping layar HP seolah sedang menempelkan pipi di tangan pasanganmu!", false},
	{687, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Dagu Bahu", "Sandarkan dagumu di bahu pasanganmu sambil tersenyum menatap layar/kaca bersama selama 20 detik!", false},
	{688, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Cute Pose", "Letakkan kedua tanganmu di bawah dagu membentuk bunga mekar dan tatap kamera dengan tatapan paling memikat!", false},
	{689, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Ujung Jari", "Berikan kecupan lembut di setiap ujung jari tangan pasanganmu satu per satu dengan penuh kasih!", false},
	{690, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Finger Kiss", "Kecup ujung jarimu satu per satu di depan kamera lalu tiupkan ke arah pasanganmu!", false},
	{691, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Bisikan", "Bisikkan dengan nada menggoda ke telinga pasanganmu satu hal yang paling ingin kamu lakukan saat kita berduaan nanti!", false},
	{692, "DARE", "PHYSICAL_TOUCH", "ONLINE", "LDR Wish", "Katakan ke kamera satu sentuhan fisik pertama yang paling ingin kamu lakukan begitu kamu memeluknya saat tiba di bandara/stasiun!", false},
	{693, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Pegang Wajah", "Pegang kedua pipi pasanganmu dengan kedua tanganmu, tatap matanya lekat-lekat, lalu katakan: 'Jangan pernah ragu sama perasaanku ya'!", false},
	{694, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Frame Screen", "Tangkap layar video call dengan kedua tanganmu di sisi kiri-kanan HP sambil tersenyum lekat menatap pasangan!", false},
	{695, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Usap Punggung", "Usap pelan punggung pasanganmu dengan pola lingkaran lembut untuk membuatnya rileks dan merasa tenang!", false},
	{696, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Sleepy Voice", "Rebahkan kepalamu di meja/kasur sambil tetap menatap kamera video call dan bicaralah dengan nada lembut berbisik selama 20 detik!", false},
	{697, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Saku Jaket", "Genggam satu tangan pasanganmu dan masukkan ke dalam saku jaket/baju bersama selama 1 putaran!", false},
	{698, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Warm Breath", "Hembuskan napas hangatmu ke arah kamera HP seolah sedang menghangatkan jemari pasangan di malam yang dingin!", false},
	{699, "DARE", "PHYSICAL_TOUCH", "OFFLINE", "Forehead Touch", "Tempelkan dahimu ke dahi pasanganmu (forehead touch) selama 15 detik sambil memejamkan mata merasakan napas berdua!", false},
	{700, "DARE", "PHYSICAL_TOUCH", "ONLINE", "Kemesraan Penuh", "Katakan dengan penuh ketulusan: 'Raga kita mungkin berjarak, tapi jiwaku selalu memelukmu erat setiap detik'!", false},
}
