package deck

import "ulartangga/models"

// QualityTimeDeck berisi 100 kartu bahasa cinta Waktu Berkualitas (50 Truth + 50 Dare)
// Dibagi ke dalam mode ONLINE (Video Call / LDR), OFFLINE (Ketemu Langsung), dan BOTH (Bisa Keduanya)
var QualityTimeDeck = []models.QuestionCard{
	// 50 TRUTH - QUALITY TIME (ID 301 - 350)
	{301, "TRUTH", "QUALITY_TIME", "BOTH", "Memori", "Momen kencan berdua mana yang paling berkesan dan ingin sekali kamu ulang kembali dari awal?", false},
	{302, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Apa definisi 'Quality Time' paling ideal bagimu ketika kita sedang menghabiskan waktu bersama?", false},
	{303, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Jika kita punya akhir pekan penuh tanpa gangguan HP dan pekerjaan, kegiatan apa yang paling ingin kamu lakukan bersamaku?", false},
	{304, "TRUTH", "QUALITY_TIME", "BOTH", "Memori", "Ceritakan obrolan larut malam (late night talk) kita yang paling membuatmu merasa terkoneksi secara mendalam!", false},
	{305, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Pernahkah kamu merasa kita sedang bersama tapi pikiran atau perhatian kita terasa berjauhan? Kapan itu?", false},
	{306, "TRUTH", "QUALITY_TIME", "BOTH", "Kencan", "Tempat atau kota impian mana yang paling ingin kamu jelajahi berdua denganku suatu saat nanti?", false},
	{307, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Apakah kamu lebih menyukai kencan jalan-jalan keluar yang ramai atau sekadar duduk santai di rumah sambil mengobrol?", false},
	{308, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Apa hal yang paling sering mengalihkan perhatianmu saat kita sedang berbicara berdua?", false},
	{309, "TRUTH", "QUALITY_TIME", "BOTH", "Memori", "Perjalanan atau liburan bersama mana yang menurutmu paling penuh tawa dan cerita tak terduga?", false},
	{310, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Kapan momen di mana keheningan di antara kita berdua tetap terasa sangat nyaman dan tidak canggung?", false},
	{311, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Hal baru apa yang ingin kamu pelajari atau coba lakukan bersama denganku tahun ini?", false},
	{312, "TRUTH", "QUALITY_TIME", "BOTH", "Kencan", "Jika kita merencanakan 'staycation' romantis, apa 3 hal wajib yang harus ada di agenda kita?", false},
	{313, "TRUTH", "QUALITY_TIME", "BOTH", "Memori", "Kapan pertama kali kita menghabiskan waktu seharian penuh berdua dan apa yang kamu rasakan saat pulang?", false},
	{314, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Apa film atau serial yang pernah kita tonton bersama dan paling banyak meninggalkan kenangan seru?", false},
	{315, "TRUTH", "QUALITY_TIME", "ONLINE", "LDR", "Seberapa sering kamu merasa rindu hanya untuk sekadar bertatapan mata langsung tanpa terhalang layar HP?", false},
	{316, "TRUTH", "QUALITY_TIME", "OFFLINE", "Kencan", "Makanan kaki lima atau warung pinggir jalan mana yang paling memiliki nilai nostalgia manis untuk kita berdua saat jalan bareng?", false},
	{317, "TRUTH", "QUALITY_TIME", "OFFLINE", "Memori", "Apakah kamu masih ingat momen saat kita terjebak hujan bersama di perjalanan? Ceritakan kenangan itu!", false},
	{318, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Topik obrolan apa yang paling kamu sukai saat kita berdiskusi santai larut malam?", false},
	{319, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Jika kita hanya memiliki waktu 1 jam sebelum berpisah lama, bagaimana kamu ingin menghabiskan 1 jam tersebut?", false},
	{320, "TRUTH", "QUALITY_TIME", "BOTH", "Kencan", "Ide kencan sederhana tanpa biaya apa yang menurutmu paling menyenangkan untuk kita lakukan?", false},
	{321, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Pernahkah kamu merasa cemburu pada kesibukan atau hobi yang menyita waktu kebersamaan kita?", false},
	{322, "TRUTH", "QUALITY_TIME", "BOTH", "Memori", "Apa foto di galeri HP-mu yang paling menangkap kehangatan momen saat kita sedang berduaan?", false},
	{323, "TRUTH", "QUALITY_TIME", "ONLINE", "LDR", "Bagi kamu saat LDR, apakah sesi video call sambil menemani masing-masing beraktivitas sudah terasa menenangkan?", false},
	{324, "TRUTH", "QUALITY_TIME", "BOTH", "Kencan", "Jika kita bisa camping di bawah bintang-bintang semalaman, apa rahasia yang ingin kamu ceritakan padaku?", false},
	{325, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Bagaimana caramu menyampaikan padaku saat kamu sedang sangat butuh kehadiran dan waktuku?", false},
	{326, "TRUTH", "QUALITY_TIME", "OFFLINE", "Memori", "Kapan momen di mana kehadiran fisikku di sampingmu terasa benar-benar menyembuhkan rasa lelahmu?", false},
	{327, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Ritual harian berdua apa yang paling ingin kamu pertahankan sampai kita tua nanti?", false},
	{328, "TRUTH", "QUALITY_TIME", "BOTH", "Kencan", "Pernahkah kita memiliki rencana kencan yang gagal total tapi justru berakhir menjadi momen yang sangat lucu?", false},
	{329, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Apakah ada impian masa kecilmu yang ingin sekali kamu wujudkan bersama denganku?", false},
	{330, "TRUTH", "QUALITY_TIME", "BOTH", "Memori", "Apa kencan pertama kita yang paling membuatmu deg-degan dari sebelum berangkat sampai tiba di rumah?", false},
	{331, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Lagu apa yang paling cocok menjadi soundtrack untuk setiap momen kebersamaan kita?", false},
	{332, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Bagaimana perasaanmu saat kita harus menjalani rutinitas harian yang padat dan jarang punya waktu luang?", false},
	{333, "TRUTH", "QUALITY_TIME", "BOTH", "Kencan", "Jika kita bisa makan malam romantis di atas kapal pesiar atau di puncak gunung, mana yang kamu pilih?", false},
	{334, "TRUTH", "QUALITY_TIME", "BOTH", "Memori", "Obrolan paling konyol apa yang pernah kita bicarakan berjam-jam sampai tidak sadar waktu sudah larut?", false},
	{335, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Apa hal yang paling kamu rindukan dari caraku menatapmu saat kita sedang duduk berhadapan?", false},
	{336, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Apa satu hal yang bisa kita perbaiki agar waktu kebersamaan kita terasa lebih bermakna dan berkualitas?", false},
	{337, "TRUTH", "QUALITY_TIME", "BOTH", "Kencan", "Apakah kamu lebih suka kencan petualangan outdoor atau kencan museum date / nonton film di bioskop?", false},
	{338, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Kenapa waktu rasanya selalu berputar terlalu cepat setiap kali kita sedang bersama?", false},
	{339, "TRUTH", "QUALITY_TIME", "ONLINE", "LDR", "Sesi nonton bareng secara virtual (watch party) mana yang paling seru pernah kita lakukan saat berjauhan?", false},
	{340, "TRUTH", "QUALITY_TIME", "OFFLINE", "Kencan", "Ketika kita jalan-jalan di mall atau pasar malam, stan mana yang paling sering membuat kita berhenti berlama-lama?", false},
	{341, "TRUTH", "QUALITY_TIME", "ONLINE", "LDR", "Bagaimana caramu membunuh rasa bosan saat video call kita sedang sama-sama hening tapi tetap ingin tersambung?", false},
	{342, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Seberapa penting menurutmu bagi kita untuk memiliki jadwal kencan rutin mingguan tanpa gangguan kerjaan?", false},
	{343, "TRUTH", "QUALITY_TIME", "OFFLINE", "Memori", "Momen naik motor atau naik mobil berdua sambil bernyanyi bersama di jalan, lagu apa yang paling berkesan?", false},
	{344, "TRUTH", "QUALITY_TIME", "ONLINE", "LDR", "Apa hal pertama yang paling ingin kamu lakukan bersamaku tepat pada hari pertama kita bertemu setelah LDR lama?", false},
	{345, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Jika ada kesempatan liburan berdua selama 3 hari tanpa gadget sama sekali, apakah kamu siap melakukannya?", false},
	{346, "TRUTH", "QUALITY_TIME", "OFFLINE", "Kencan", "Kapan terakhir kali kita duduk berdua di bangku taman atau pinggir pantai menikmati pemandangan matahari tenggelam?", false},
	{347, "TRUTH", "QUALITY_TIME", "ONLINE", "LDR", "Berapa lama rekor video call terlama yang pernah kita lakukan dan topik apa saja yang kita obrolkan saat itu?", false},
	{348, "TRUTH", "QUALITY_TIME", "BOTH", "Deep Talk", "Apa tanda-tanda yang paling terlihat dariku saat aku sedang lelah dan butuh ditemani secara intensif?", false},
	{349, "TRUTH", "QUALITY_TIME", "BOTH", "Memori", "Makanan apa yang proses memasak atau mencarinya bersama-sama paling meninggalkan kenangan seru?", false},
	{350, "TRUTH", "QUALITY_TIME", "BOTH", "Romantis", "Apa arti 'hadir seutuhnya' untuk pasangan bagimu di era di mana semua orang terpaku pada layar ponsel?", false},

	// 50 DARE - QUALITY TIME (ID 351 - 400)
	{351, "DARE", "QUALITY_TIME", "BOTH", "Fokus", "Tatap mata pasanganmu lekat-lekat selama 30 detik tanpa boleh berbicara, tertawa, atau mengalihkan pandangan!", false},
	{352, "DARE", "QUALITY_TIME", "BOTH", "Detoks", "Tengkurapkan layar HP kalian berdua (jangan sentuh notifikasi sama sekali) selama 3 putaran game ke depan!", false},
	{353, "DARE", "QUALITY_TIME", "BOTH", "Memori", "Ceritakan kembali detik-detik kencan pertama kita secara mendetail mulai dari pakaian hingga obrolan pertama!", false},
	{354, "DARE", "QUALITY_TIME", "BOTH", "Romantis", "Putar satu lagu kenangan cinta kita di HP dan nikmati lagunya bersama sambil saling menatap hangat!", false},
	{355, "DARE", "QUALITY_TIME", "BOTH", "Kencan", "Bikin rencana konkret untuk kencan berikutnya (tentukan hari, jam, tempat, dan outfit) sekarang juga!", false},
	{356, "DARE", "QUALITY_TIME", "BOTH", "Deep Talk", "Tanyakan satu pertanyaan tentang masa kecil pasangan yang belum pernah kamu tanyakan sebelumnya!", false},
	{357, "DARE", "QUALITY_TIME", "BOTH", "Fokus", "Duduk berhadapan, pegang tangan pasangan (atau tatap di kamera), dan dengarkan dia bercerita selama 1 menit tanpa menyela!", false},
	{358, "DARE", "QUALITY_TIME", "OFFLINE", "Romantis", "Bikin teh atau kopi hangat dan nikmati berdua secara santai sambil duduk berdampingan!", false},
	{359, "DARE", "QUALITY_TIME", "ONLINE", "LDR", "Ambil cangkir minumanmu masing-masing, lakukan 'virtual toast' (tos cangkir ke kamera HP) dan minum bersamaan!", false},
	{360, "DARE", "QUALITY_TIME", "BOTH", "Kencan", "Buat daftar 'Bucket List 5 Tempat Kencan Impian' yang wajib kita kunjungi bersama dalam setahun ke depan!", false},
	{361, "DARE", "QUALITY_TIME", "BOTH", "Memori", "Buka album foto di HP, cari foto berdua paling konyol atau paling romantis, lalu ceritakan kisah di balik foto itu!", false},
	{362, "DARE", "QUALITY_TIME", "OFFLINE", "Romantis", "Ajak pasangan berdansa lambat (slow dance) tanpa musik selama 30 detik di ruangan kalian berada!", false},
	{363, "DARE", "QUALITY_TIME", "ONLINE", "LDR", "Putar lagu romantis dan lakukan 'virtual slow dance' di depan kamera dengan gerakan lembut saling berhadapan!", false},
	{364, "DARE", "QUALITY_TIME", "BOTH", "Deep Talk", "Ungkapkan satu ketakutan terbesarmu dalam hidup dan dengarkan respons penuh empati dari pasanganmu!", false},
	{365, "DARE", "QUALITY_TIME", "BOTH", "Fokus", "Tutup matamu selama 20 detik dan sebutkan 3 hal tentang pasanganmu yang paling kamu syukuri hadir di hidupmu!", false},
	{366, "DARE", "QUALITY_TIME", "BOTH", "Kencan", "Simulasikan kencan kilat (speed dating): berpura-pura baru kenal dan saling merayu dalam waktu 45 detik!", false},
	{367, "DARE", "QUALITY_TIME", "BOTH", "Romantis", "Sebutkan 3 hal sederhana dalam keseharian yang selalu terasa jauh lebih indah saat dilakukan berdua dengannya!", false},
	{368, "DARE", "QUALITY_TIME", "BOTH", "Memori", "Tirukan percakapan lucu atau canggung saat pertama kali kalian saling bertukar kontak telepon/sosmed!", false},
	{369, "DARE", "QUALITY_TIME", "BOTH", "Fokus", "Lakukan sinkronisasi napas berdua: tarik dan hembuskan napas secara bersamaan sebanyak 5 kali putaran!", false},
	{370, "DARE", "QUALITY_TIME", "BOTH", "Kencan", "Rancang menu makan malam romantis yang akan kalian masak/makan bersama pada kencan akhir pekan nanti!", false},
	{371, "DARE", "QUALITY_TIME", "BOTH", "Deep Talk", "Sampaikan satu harapan paling tulus untuk kebersamaan kita 5 tahun dari sekarang!", false},
	{372, "DARE", "QUALITY_TIME", "BOTH", "Romantis", "Nyanyikan sepenggal lagu pengantar tidur yang lembut khusus untuk pasanganmu!", false},
	{373, "DARE", "QUALITY_TIME", "BOTH", "Memori", "Sebutkan tempat makan favorit kita berdua dan urutkan 3 menu yang paling sering kita pesan bersama!", false},
	{374, "DARE", "QUALITY_TIME", "OFFLINE", "Fokus", "Letakkan kepalamu di pundak pasanganmu dan pejamkan mata selama 30 detik untuk merasakan kenyamanan!", false},
	{375, "DARE", "QUALITY_TIME", "ONLINE", "LDR", "Tempelkan pipimu ke layar HP seolah-olah sedang bersandar di bahu pasangan sambil tersenyum manja!", false},
	{376, "DARE", "QUALITY_TIME", "BOTH", "Kencan", "Buat janji temu kencan tanpa gadget sama sekali untuk hari libur terdekat!", false},
	{377, "DARE", "QUALITY_TIME", "BOTH", "Romantis", "Bikin tebak-tebakan kenangan: tebak apa yang kamu kenakan saat kencan kedua kita!", false},
	{378, "DARE", "QUALITY_TIME", "BOTH", "Deep Talk", "Ceritakan satu momen di mana kamu merasa sangat beruntung tidak melewatkan kesempatan mengenalnya!", false},
	{379, "DARE", "QUALITY_TIME", "OFFLINE", "Fokus", "Pegang pipi pasangan dengan kedua tanganmu dan katakan: 'Saat ini, duniaku cuma ada kamu'!", false},
	{380, "DARE", "QUALITY_TIME", "ONLINE", "LDR", "Letakkan kedua telapak tanganmu membingkai layar video call tepat di posisi wajah pasanganmu selama 15 detik!", false},
	{381, "DARE", "QUALITY_TIME", "BOTH", "Kencan", "Pilih satu film romantis di aplikasi streaming yang wajib kalian tonton bersama minggu ini!", false},
	{382, "DARE", "QUALITY_TIME", "BOTH", "Memori", "Kisah ulang momen paling mendebarkan saat kamu menunggu kedatangan atau telepon pasanganmu!", false},
	{383, "DARE", "QUALITY_TIME", "BOTH", "Romantis", "Bikin janji lisan: 'Aku akan selalu meluangkan waktu khusus untukmu di tengah kesibukanku'!", false},
	{384, "DARE", "QUALITY_TIME", "BOTH", "Deep Talk", "Diskusikan satu kebiasaan baru yang ingin kita mulai bersama untuk mempererat ikatan batin!", false},
	{385, "DARE", "QUALITY_TIME", "BOTH", "Fokus", "Tatap pasanganmu dan ceritakan apa hal yang paling kamu kagumi dari ketenangannya!", false},
	{386, "DARE", "QUALITY_TIME", "BOTH", "Kencan", "Bikin jadwal 'jalan santai pagi atau sore' berdua keliling taman terdekat akhir pekan ini!", false},
	{387, "DARE", "QUALITY_TIME", "BOTH", "Memori", "Tirukan ekspresi wajah pasangan saat dia sedang asyik menonton sesuatu atau sedang lapar!", false},
	{388, "DARE", "QUALITY_TIME", "BOTH", "Romantis", "Sampaikan ucapan terima kasih karena pasangan selalu meluangkan waktunya untuk menemanimu!", false},
	{389, "DARE", "QUALITY_TIME", "BOTH", "Deep Talk", "Ungkapkan impian rumah tinggal masa depan kita berdua (lokasi, suasana, dan ruangan favorit)!", false},
	{390, "DARE", "QUALITY_TIME", "BOTH", "Fokus", "Tersenyumlah bersama sambil menatap wajah satu sama lain selama 20 detik penuh ketulusan!", false},
	{391, "DARE", "QUALITY_TIME", "BOTH", "Romantis", "Katakan: 'Bersamamu, waktu yang berjam-jam selalu terasa seperti hitungan detik'!", false},
	{392, "DARE", "QUALITY_TIME", "ONLINE", "LDR", "Ajak pasangan main game tebak kata lewat chat/video call selama 1 menit sekarang juga!", false},
	{393, "DARE", "QUALITY_TIME", "OFFLINE", "Kencan", "Pegang erat tangan pasangan dan ajak dia berjalan berputar mengelilingi ruangan dengan langkah pelan!", false},
	{394, "DARE", "QUALITY_TIME", "ONLINE", "LDR", "Kirimkan foto pemandangan langit atau kamar tempatmu berada sekarang sebagai tanda kehadiran bersama!", false},
	{395, "DARE", "QUALITY_TIME", "BOTH", "Deep Talk", "Tanyakan 'Apa hal yang paling ingin kamu capai bersamaku sebelum tahun ini berganti?'!", false},
	{396, "DARE", "QUALITY_TIME", "BOTH", "Romantis", "Ungkapkan 1 lagu yang paling ingin kamu nyanyikan bersama saat sedang perjalanan jauh berdua!", false},
	{397, "DARE", "QUALITY_TIME", "ONLINE", "LDR", "Sepakati waktu 'Date Night Virtual' minggu ini lengkap dengan pakaian rapi dan lilin aroma!", false},
	{398, "DARE", "QUALITY_TIME", "OFFLINE", "Fokus", "Duduk bersandar berdua dalam hening selama 45 detik tanpa suara handphone!", false},
	{399, "DARE", "QUALITY_TIME", "BOTH", "Memori", "Sebutkan 3 tempat paling bersejarah bagi perjalanan cinta kita berdua!", false},
	{400, "DARE", "QUALITY_TIME", "BOTH", "Komitmen", "Ucapkan komitmen: 'Aku berjanji akan selalu hadir dengan hati seutuhnya saat bersamamu'!", false},
}
