package deck

import "ulartangga/models"

// ReceivingGiftsDeck berisi 100 kartu bahasa cinta Penerimaan Hadiah (50 Truth + 50 Dare)
// Dibagi ke dalam mode ONLINE (Video Call / LDR), OFFLINE (Ketemu Langsung), dan BOTH (Bisa Keduanya)
var ReceivingGiftsDeck = []models.QuestionCard{
	// 50 TRUTH - RECEIVING GIFTS (ID 401 - 450)
	{401, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Memori", "Kado atau hadiah pertama apa yang pernah kuberikan padamu dan masih kamu simpan rapi sampai sekarang?", false},
	{402, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Sentimental", "Bagi kamu, apakah nilai sebuah hadiah dilihat dari harganya atau dari perhatian dan makna di baliknya?", false},
	{403, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Kejutan", "Kejutan kecil apa yang pernah kuberikan tanpa hari spesial yang paling membuat hatimu tersentuh?", false},
	{404, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Impian", "Jika kamu bisa meminta satu hadiah impian dariku tanpa memikirkan budget, hadiah apa yang paling kamu inginkan?", false},
	{405, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Memori", "Barang apa pemberianku yang paling sering kamu pakai atau bawa ke mana-mana dalam keseharianmu?", false},
	{406, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Sentimental", "Apakah kamu lebih menyukai kado buatan tangan (DIY / surat cinta) atau kado barang fungsional yang langsung bisa dipakai?", false},
	{407, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Kejutan", "Pernahkah kamu diam-diam menginginkan suatu barang dan berharap aku bisa peka membelikannya untukmu?", false},
	{408, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Deep Talk", "Bagaimana perasaanmu ketika menerima hadiah yang dibungkus dengan penuh usaha dan kartu ucapan tulisan tangan?", false},
	{409, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Memori", "Kado ulang tahun mana dariku yang menurutmu paling tidak terduga dan paling sukses membuatmu terharu?", false},
	{410, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Sentimental", "Apa arti cinderamata atau oleh-oleh kecil yang kubawakan saat aku pulang dari bepergian jauh bagimu?", false},
	{411, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Impian", "Jika kita memiliki rumah sendiri, pernak-pernik atau hadiah apa yang ingin kamu pajang sebagai simbol cinta kita?", false},
	{412, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Kejutan", "Pernahkah aku salah membelikan hadiah atau memilih warna yang kurang kamu sukai? Bagaimana reaksimu saat itu?", false},
	{413, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Memori", "Bunga, cokelat, atau makanan apa yang pernah kuberikan yang rasanya paling manis di ingatanmu?", false},
	{414, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Sentimental", "Apakah kamu masih menyimpan tiket bioskop, struk belanja, atau pembungkus kado kencan masa lalu kita?", false},
	{415, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Deep Talk", "Kenapa menurutmu memberi hadiah adalah bentuk bahasa kasih yang menguatkan memori hubungan?", false},
	{416, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Impian", "Hadiah pengalaman (seperti tiket konser berdua atau tiket liburan) apa yang paling ingin kamu dapatkan dariku?", false},
	{417, "TRUTH", "RECEIVING_GIFTS", "ONLINE", "LDR", "Kapan terakhir kali kamu merasa sangat senang saat tiba-tiba ada kurir paket datang mengantarkan makanan/kado dariku saat LDR?", false},
	{418, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Memori", "Hadiah apa yang pernah kamu persiapkan untukku yang persiapannya paling menguras tenaga dan pikiranmu?", false},
	{419, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Sentimental", "Benda kecil apa yang jika kamu lihat di suatu toko, langsung membuatmu teringat padaku?", false},
	{420, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Deep Talk", "Bagaimana caramu menunjukkan apresiasi ketika pasangan memberikan sesuatu yang sangat kamu sukai?", false},
	{421, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Impian", "Buku, perhiasan, atau aksesoris couple apa yang paling ingin kita miliki bersama?", false},
	{422, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Kejutan", "Apakah kamu tipe orang yang suka kejutan mendadak atau lebih suka ditanya dulu sebelum dibelikan hadiah?", false},
	{423, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Memori", "Hadiah paling lucu atau konyol apa yang pernah kita saling tukarkan selama berhubungan?", false},
	{424, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Sentimental", "Seberapa berharga surat cinta atau sticky note kecil yang diselipkan di tas atau barang bawaanmu?", false},
	{425, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Deep Talk", "Pernahkah kamu merasa canggung atau tidak enak hati saat menerima hadiah yang terlalu mewah dariku?", false},
	{426, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Impian", "Jika kamu bisa mendesain kado anniversary impian untuk kita, wujud kado itu seperti apa?", false},
	{427, "TRUTH", "RECEIVING_GIFTS", "ONLINE", "LDR", "Makanan manis atau minuman apa yang jika kupesankan lewat ojek online langsung ampuh memperbaiki mood-mu saat suntuk?", false},
	{428, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Memori", "Apa barang termurah yang pernah kuberikan tapi memiliki tempat paling istimewa di hatimu?", false},
	{429, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Sentimental", "Jika terjadi musibah dan kamu hanya bisa menyelamatkan 1 barang pemberianku, barang mana yang kamu selamatkan?", false},
	{430, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Deep Talk", "Apakah menerima hadiah membuatmu merasa aku selalu memikirkanmu bahkan saat sedang berjauhan?", false},
	{431, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Impian", "Tanaman atau hewan peliharaan apa yang ingin kita rawat bersama sebagai hadiah kehidupan di hubungan kita?", false},
	{432, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Kejutan", "Ceritakan ekspresi wajahmu saat pertama kali membuka kotak kado dariku!", false},
	{433, "TRUTH", "RECEIVING_GIFTS", "OFFLINE", "Memori", "Baju atau jaket milikku yang pernah kamu pinjam/minta saat ketemu dan sampai sekarang masih kamu simpan?", false},
	{434, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Sentimental", "Pernahkah aroma parfum dari kado yang kuberikan membuatmu langsung merasa aman dan tenang?", false},
	{435, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Deep Talk", "Apa tradisi tukar kado yang ingin kita lestarikan setiap perayaan ulang tahun hubungan kita?", false},
	{436, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Impian", "Parfum dengan aroma seperti apa yang paling kamu inginkan kusemprotkan saat kita bertemu?", false},
	{437, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Kejutan", "Apa jenis kejutan anniversary yang paling membuatmu terpesona sepanjang ingatanmu?", false},
	{438, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Sentimental", "Kenapa setiap kado dariku selalu terasa memiliki jiwa dan cinta di dalamnya?", false},
	{439, "TRUTH", "RECEIVING_GIFTS", "ONLINE", "LDR", "Kado virtual apa (playlist, video kompilasi foto, atau surat digital) yang paling membuatmu terharu saat LDR?", false},
	{440, "TRUTH", "RECEIVING_GIFTS", "OFFLINE", "Sentimental", "Ketika kita jalan bersama di toko souvenir, cinderamata apa yang paling ingin kamu beli untuk dipajang di kamar?", false},
	{441, "TRUTH", "RECEIVING_GIFTS", "ONLINE", "LDR", "Bagaimana perasaanmu ketika paket kirimanku tiba dan kamu membukanya sambil video call bersamaku?", false},
	{442, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Impian", "Gadget atau barang penunjang hobi apa yang paling ingin kamu belikan untuk pasanganmu jika gajian berlebih?", false},
	{443, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Memori", "Apakah kamu masih ingat kartu ucapan pertama yang pernah kuberikan dan kata-kata apa yang tertulis di situ?", false},
	{444, "TRUTH", "RECEIVING_GIFTS", "OFFLINE", "Kejutan", "Pernahkah aku menyembunyikan kado di saku bajumu atau di dalam tasmu tanpa kamu sadari?", false},
	{445, "TRUTH", "RECEIVING_GIFTS", "ONLINE", "LDR", "Seberapa sering kamu mengirimkan link barang di marketplace sambil memberikan kode 'Lucu ya sayang'?", false},
	{446, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Deep Talk", "Menurutmu, apa hadiah emosional terbaik yang bisa kita berikan satu sama lain setiap hari?", false},
	{447, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Sentimental", "Benda apa milik pasanganmu yang baunya paling sering kamu hirup saat sedang dilanda rindu?", false},
	{448, "TRUTH", "RECEIVING_GIFTS", "OFFLINE", "Memori", "Bunga mawar atau bunga jenis apa yang pernah kamu terima langsung dari tanganku?", false},
	{449, "TRUTH", "RECEIVING_GIFTS", "ONLINE", "LDR", "Kado digital apa yang paling ingin kamu dapatkan untuk merayakan hari jadian kita bulan ini?", false},
	{450, "TRUTH", "RECEIVING_GIFTS", "BOTH", "Romantis", "Apa arti sebuah cincin atau gelang komitmen di jarimu sebagai lambang cinta kita berdua?", false},

	// 50 DARE - RECEIVING GIFTS (ID 451 - 500)
	{451, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Kreatif", "Buat origami hati atau lipatan bunga dari kertas/tisu dalam waktu 60 detik dan berikan langsung ke pasanganmu!", false},
	{452, "DARE", "RECEIVING_GIFTS", "ONLINE", "Virtual", "Kirimkan 'Voucher Hadiah Cinta Virtual' lewat chat WA (misal: 'Voucher Traktir Kopi Online Besok Pagi') sekarang!", false},
	{453, "DARE", "RECEIVING_GIFTS", "BOTH", "Janji", "Janjikan satu traktiran makanan atau minuman kesukaan pasanganmu untuk kencan/pertemuan berikutnya (catat di notes)!", false},
	{454, "DARE", "RECEIVING_GIFTS", "ONLINE", "Musik", "Buatkan mini playlist 3 lagu di Spotify/YouTube yang liriknya mendeskripsikan hadiah perasaanmu padanya dan kirim linknya!", false},
	{455, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Spontan", "Cari satu benda kecil di sekitarmu, berikan kepada pasangan dengan cerita fiktif romantis seolah itu pusaka cinta!", false},
	{456, "DARE", "RECEIVING_GIFTS", "ONLINE", "LDR", "Kirimkan saldo e-wallet (GoPay/OVO/ShopeePay) nominal berapapun dengan catatan: 'Buat beli jajan manis hari ini ya sayang'!", false},
	{457, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Romantis", "Lepaskan aksesoris kecil milikmu (cincin, gelang, atau kuncir rambut) dan kenakan pada pasanganmu sebagai tanda cinta!", false},
	{458, "DARE", "RECEIVING_GIFTS", "ONLINE", "Kreatif", "Gambarkan sketsa wajah pasanganmu di secarik kertas dalam 1 menit, foto atau tunjukkan ke kamera video call!", false},
	{459, "DARE", "RECEIVING_GIFTS", "BOTH", "Janji", "Bikin voucher virtual 'Bebas Ngambek 1 Kali' dan tanda tangani secara resmi lewat chat untuk pasanganmu!", false},
	{460, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Romantis", "Kumpulkan 3 barang di ruangan ini yang berwarna favorit pasanganmu dan persembahkan di hadapannya!", false},
	{461, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Surat", "Tuliskan satu surat cinta mini 3 baris di kertas/tisu, gulung rapi, dan masukkan ke kantong baju pasanganmu!", false},
	{462, "DARE", "RECEIVING_GIFTS", "ONLINE", "LDR", "Kirimkan pesan panjang berisi 5 hal yang ingin kamu belikan untuk pasangan saat kita punya rezeki melimpah kelak!", false},
	{463, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Kreatif", "Bikin cincin darurat dari kertas atau tangkai dan pasangkan di jari manis pasanganmu!", false},
	{464, "DARE", "RECEIVING_GIFTS", "ONLINE", "Marketplace", "Buka marketplace, cari barang yang paling diinginkan pasangan di wishlist-nya, screenshot dan katakan: 'Pasti akan kubeliin buat kamu'!", false},
	{465, "DARE", "RECEIVING_GIFTS", "BOTH", "Romantis", "Berikan pasanganmu 'Hadiah Keheningan & Tatapan Penuh Kasih' selama 30 detik tanpa sepatah kata pun terucap!", false},
	{466, "DARE", "RECEIVING_GIFTS", "BOTH", "Janji", "Kirimkan stiker kupon 'Satu Hari Bebas Pilih Tempat Makan' ke chat pribadi kalian!", false},
	{467, "DARE", "RECEIVING_GIFTS", "BOTH", "Kreatif", "Ciptakan pantun bertema hadiah yang berakhiran nama kado impian pasanganmu!", false},
	{468, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Spontan", "Suapkan satu camilan atau berikan minumanmu kepada pasanganmu seperti mempersembahkan jamuan istimewa!", false},
	{469, "DARE", "RECEIVING_GIFTS", "ONLINE", "LDR", "Kirim foto selfie dengan pose membentuk simbol love besar dengan tanganmu khusus untuk pasanganmu simpan!", false},
	{470, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Romantis", "Berikan satu kecupan lembut di kening pasangan sebagai 'hadiah terhangat' untuk menenangkan pikirannya!", false},
	{471, "DARE", "RECEIVING_GIFTS", "ONLINE", "Virtual", "Kirimkan stiker hadiah bergerak paling imut di WhatsApp ke pasanganmu sekarang!", false},
	{472, "DARE", "RECEIVING_GIFTS", "BOTH", "Janji", "Janjikan untuk membersihkan atau merapikan salah satu barang kesayangan pasanganmu akhir pekan ini!", false},
	{473, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Kreatif", "Bungkus barang kecil di mejamu menggunakan tisu dengan pita darurat dan serahkan secara khidmat!", false},
	{474, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Spontan", "Bawakan jaket atau selimut untuk pasanganmu agar dia merasa hangat dan terlindungi!", false},
	{475, "DARE", "RECEIVING_GIFTS", "BOTH", "Surat", "Tuliskan pesan terima kasih atas semua kado yang pernah kamu terima darinya di buku catatan atau chat!", false},
	{476, "DARE", "RECEIVING_GIFTS", "BOTH", "Romantis", "Pegang tangan pasangan (atau tatap di kamera) dan katakan: 'Hadiah terindah dalam hidupku bukan benda, tapi keberadaanmu'!", false},
	{477, "DARE", "RECEIVING_GIFTS", "ONLINE", "Virtual", "Cari link video hewan lucu favoritnya di medsos dan kirimkan sebagai hadiah pencerah suasana hati!", false},
	{478, "DARE", "RECEIVING_GIFTS", "BOTH", "Janji", "Bikin janji tertulis: 'Voucher Nonton Film Apapun Pilihanmu Tanpa Protes'!", false},
	{479, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Kreatif", "Tuliskan kata 'I LOVE YOU' di secarik kertas kecil lalu sembunyikan di dompet atau casing HP pasangan!", false},
	{480, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Spontan", "Pijat lembut telapak tangan pasanganmu sebagai hadiah relaksasi instan selama 1 menit!", false},
	{481, "DARE", "RECEIVING_GIFTS", "ONLINE", "LDR", "Kirim pesanan makanan manis atau minuman kejutan via aplikasi pesan antar ke alamat pasangan sekarang juga!", false},
	{482, "DARE", "RECEIVING_GIFTS", "BOTH", "Romantis", "Hadiahkan tatapan mata penuh rasa syukur selama 20 detik tanpa boleh tersenyum sinis!", false},
	{483, "DARE", "RECEIVING_GIFTS", "BOTH", "Virtual", "Ganti nada dering kontak pasanganmu dengan lagu romantis dan buktikan dengan menelponnya!", false},
	{484, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Kreatif", "Bikin tebak kado: minta pasangan menebak barang apa yang ada di kantong atau genggaman tanganmu!", false},
	{485, "DARE", "RECEIVING_GIFTS", "BOTH", "Janji", "Tuliskan kupon: 'Voucher Sarapan Pagi Dibuatkan / Dibelikan' untuk besok pagi!", false},
	{486, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Spontan", "Kecup punggung tangan pasangan dan ucapkan: 'Kado terbaik adalah senyuman manismu'!", false},
	{487, "DARE", "RECEIVING_GIFTS", "ONLINE", "LDR", "Tiupkan kecupan manis ke arah kamera sambil membuat bentuk hati dengan kedua tanganmu!", false},
	{488, "DARE", "RECEIVING_GIFTS", "BOTH", "Janji", "Janjikan sebuah kado kejutan yang akan kamu kirimkan ke rumahnya sebelum akhir bulan ini!", false},
	{489, "DARE", "RECEIVING_GIFTS", "ONLINE", "LDR", "Buat desain gambar lucu di aplikasi Instagram Stories/Canva bertuliskan nama kalian berdua dan kirimkan ke chat!", false},
	{490, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Romantis", "Semprotkan sedikit parfummu ke sapu tangan/tisu dan selipkan ke dalam tas pasangan agar dia selalu mengingatmu!", false},
	{491, "DARE", "RECEIVING_GIFTS", "BOTH", "Virtual", "Kirimkan meme pasangan yang paling manis dan lucu yang bisa kamu temukan di galeri/internet!", false},
	{492, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Spontan", "Rapikan barang bawaan pasangan dan letakkan permen manis di dalam sakunya!", false},
	{493, "DARE", "RECEIVING_GIFTS", "ONLINE", "LDR", "Kirim rekaman suara berbisik: 'Hadiah terbesarku adalah bisa mendengar suaramu setiap hari'!", false},
	{494, "DARE", "RECEIVING_GIFTS", "BOTH", "Kreatif", "Tuliskan 'Surat Voucher Kencan Bebas Cemberut Selama 24 Jam' dan kirimkan ke pasangan!", false},
	{495, "DARE", "RECEIVING_GIFTS", "BOTH", "Janji", "Tanyakan 'Barang apa yang lagi paling kamu butuhin saat ini?' dan masukkan ke daftar belanjamu!", false},
	{496, "DARE", "RECEIVING_GIFTS", "ONLINE", "LDR", "Bikin video time-lapse 10 detik kamu sedang melambaikan tangan dengan senyum termanis untuk pasangan!", false},
	{497, "DARE", "RECEIVING_GIFTS", "OFFLINE", "Romantis", "Kalungkan tanganmu di leher pasangan dan hadiahkan pelukan hangat selama 30 detik!", false},
	{498, "DARE", "RECEIVING_GIFTS", "BOTH", "Kado Emosi", "Ungkapkan 3 alasan kenapa hadiah terindah yang pernah kamu terima adalah kehadiran dirinya!", false},
	{499, "DARE", "RECEIVING_GIFTS", "BOTH", "Janji", "Sepakati kado anniversary yang akan kalian buat sendiri (handmade) untuk perayaan berikutnya!", false},
	{500, "DARE", "RECEIVING_GIFTS", "BOTH", "Komitmen", "Ucapkan komitmen: 'Aku akan selalu berusaha memberikan yang terbaik untuk kebahagiaanmu'!", false},
}
