package deck

import "ulartangga/models"

// WordsOfAffirmationDeck berisi 100 kartu bahasa cinta Pujian Lewat Kata-kata (50 Truth + 50 Dare)
// Dibagi ke dalam mode ONLINE (Video Call / LDR), OFFLINE (Ketemu Langsung), dan BOTH (Bisa Keduanya)
var WordsOfAffirmationDeck = []models.QuestionCard{
	// 50 TRUTH - WORDS OF AFFIRMATION (ID 201 - 250)
	{201, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Pujian tulus apa dariku yang pernah kamu dengar dan paling membuat hatimu berbunga-bunga sampai sekarang?", false},
	{202, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Kalimat penyemangat apa dariku yang paling ampuh menenangkanmu saat kamu sedang merasa gagal atau tertekan?", false},
	{203, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Apa panggilan sayang dariku yang paling membuatmu merasa dicintai dan istimewa?", false},
	{204, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Sebutkan satu kelebihan fisik dan satu kelebihan karakter dariku yang paling membuatmu bangga memilikiku!", false},
	{205, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Deep Talk", "Kapan terakhir kali kata-kataku tanpa sengaja membuatmu tersentuh hingga meneteskan air mata haru?", false},
	{206, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Apa hal yang paling ingin kamu dengar dariku ketika suasana hatimu sedang sangat buruk?", false},
	{207, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Jika ada satu kalimat yang bisa kurangkai untuk selalu mengingatkanmu bahwa kamu berharga, kalimat apa itu?", false},
	{208, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Apa bakat atau kemampuan unik dariku yang menurutmu sangat keren dan menginspirasimu?", false},
	{209, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Deep Talk", "Pernahkah kamu merasa kekurangan kata-kata pujian atau apresiasi dariku? Di momen apa itu terjadi?", false},
	{210, "TRUTH", "WORDS_OF_AFFIRMATION", "ONLINE", "Romantis", "Apa pesan chat terpanjang dariku saat LDR yang paling berkesan dan masih sering kamu baca ulang di HP-mu?", false},
	{211, "TRUTH", "WORDS_OF_AFFIRMATION", "ONLINE", "Pujian", "Bagian mana dari caraku menyapa lewat telepon/video call yang paling kamu rindukan setiap harinya?", false},
	{212, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Usaha kecil apa yang pernah kulakukan yang sangat kamu syukuri namun belum sempat kamu ucapkan terima kasih?", false},
	{213, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Jika suaraku diibaratkan melodi lagu, melodi seperti apa yang paling menggambarkan rasa nyamanmu bersamaku?", false},
	{214, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Bagaimana caraku bersabar menghadapimu yang membuatmu merasa sangat dimengerti dan dihargai?", false},
	{215, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Deep Talk", "Kalimat apa yang paling kamu takuti keluar dari mulutku dalam hubungan kita?", false},
	{216, "TRUTH", "WORDS_OF_AFFIRMATION", "ONLINE", "Pujian", "Di layar video call ini, bagian wajah atau senyumanku mana yang terlihat paling manis hari ini?", false},
	{217, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Apa pengakuan cinta pertamaku yang paling membuat jantungmu berdebar hebat?", false},
	{218, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Apa satu nasihat bijak dariku yang selalu kamu ingat dan kamu terapkan dalam kehidupan sehari-harimu?", false},
	{219, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Menurutmu, apa hal paling menarik dari caraku memandang dan merespons kehidupan?", false},
	{220, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Deep Talk", "Seberapa besar arti ucapan 'Aku bangga sama kamu' dariku bagi rasa percaya dirimu?", false},
	{221, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Apa gombalan paling receh dariku yang awalnya bikin kamu geleng-geleng tapi ujungnya bikin salting?", false},
	{222, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Saat kamu berhasil mencapai suatu impian, kenapa ucapan selamat dariku terasa paling berharga?", false},
	{223, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Hal apa dari senyuman atau tawaku yang paling sering membuat harimu yang redup menjadi cerah?", false},
	{224, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Deep Talk", "Apakah kamu merasa sudah cukup mendengar kata 'Terima kasih' dan 'Maaf' dariku? Jelaskan rasanya!", false},
	{225, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Apa tiga kata sifat yang menurutmu paling mendeskripsikan kebaikan hatiku?", false},
	{226, "TRUTH", "WORDS_OF_AFFIRMATION", "ONLINE", "Apresiasi", "Ceritakan momen di mana satu voice note atau chat 'Semangat ya sayang' dariku benar-benar menyelamatkan harimu saat LDR!", false},
	{227, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Apa keputusan terbesar yang pernah kuambil yang membuatmu semakin menaruh rasa hormat padaku?", false},
	{228, "TRUTH", "WORDS_OF_AFFIRMATION", "OFFLINE", "Pujian", "Saat kita duduk berdekatan seperti ini, aroma atau wangi parfumku mana yang paling bikin kamu betah?", false},
	{229, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Deep Talk", "Bagaimana caraku menegurmu saat salah yang paling bisa kamu terima tanpa merasa tersinggung?", false},
	{230, "TRUTH", "WORDS_OF_AFFIRMATION", "ONLINE", "Romantis", "Apa kalimat penutup telepon atau 'good night' dariku sebelum tidur yang paling bikin kamu tidur nyenyak?", false},
	{231, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Apa hal yang paling kamu sukai dari caraku memperkenalkanmu kepada orang lain?", false},
	{232, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Kapan kamu merasa diriku terlihat paling dewasa, bijaksana, dan bisa diandalkan?", false},
	{233, "TRUTH", "WORDS_OF_AFFIRMATION", "OFFLINE", "Pujian", "Saat kita bertatapan langsung di ruangan ini, apa yang paling terpancar dari mataku yang membuatmu luluh?", false},
	{234, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Deep Talk", "Pernahkah kamu meragukan ketulusan kata cintaku? Kapan itu dan apa yang mengembalikan keyakinanmu?", false},
	{235, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Jika kamu harus menulis surat cinta singkat untukku sekarang, kalimat pembuka apa yang akan kamu tulis?", false},
	{236, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Sebutkan satu pengorbananku yang menurutmu sangat besar dan tak ternilai harganya!", false},
	{237, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Apa ketabahan atau ketegaran dariku yang paling membuatmu terpukau dan termotivasi?", false},
	{238, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Kenapa kamu merasa kata-kata cintaku berbeda dari siapapun yang pernah hadir di masa lalumu?", false},
	{239, "TRUTH", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Kata-kata apa dariku yang paling sering kamu baca ulang saat kamu merasa kesepian di perantauan?", false},
	{240, "TRUTH", "WORDS_OF_AFFIRMATION", "OFFLINE", "Pujian", "Ketika kita berjalan berdampingan di tempat umum, pujian apa yang paling ingin kamu dengar dariku?", false},
	{241, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Deep Talk", "Apakah ada kalimat masa lalu yang pernah melukai hatimu dan ingin kamu dengar kata maafnya lagi sekarang?", false},
	{242, "TRUTH", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Apa pesan penyemangat pertama yang paling kamu tunggu setiap kali membuka HP di pagi hari?", false},
	{243, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Jika cinta kita diibaratkan satu kalimat slogan, slogan apa yang paling pas?", false},
	{244, "TRUTH", "WORDS_OF_AFFIRMATION", "OFFLINE", "Pujian", "Apa hal yang paling kamu sukai dari suaraku ketika aku berbisik langsung tepat di sebelahmu?", false},
	{245, "TRUTH", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Seberapa besar arti telepon rutin di sela jam istirahat untuk menjaga hatimu tetap tenang?", false},
	{246, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Bagian mana dari kejujuran dan keterbukaanku yang paling membuatmu merasa aman?", false},
	{247, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Pernahkah caraku membela dirimu di hadapan orang lain membuatmu merasa sangat dihargai?", false},
	{248, "TRUTH", "WORDS_OF_AFFIRMATION", "OFFLINE", "Romantis", "Saat kita saling berhadapan tanpa layar, apa kalimat pertama yang selalu terbersit di dalam benakmu?", false},
	{249, "TRUTH", "WORDS_OF_AFFIRMATION", "ONLINE", "Pujian", "Apa ekspresi wajahku di kamera video call yang paling sering bikin kamu gemas sendiri?", false},
	{250, "TRUTH", "WORDS_OF_AFFIRMATION", "BOTH", "Deep Talk", "Apa janji masa depan yang pernah kuucapkan yang paling kamu jaga erat di dalam hatimu?", false},

	// 50 DARE - WORDS OF AFFIRMATION (ID 251 - 300)
	{251, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Tatap mata pasanganmu (lewat layar atau langsung) dan berikan 5 pujian spesifik tentang paras wajahnya tanpa jeda berpikir!", false},
	{252, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Kirim voice note 20 detik sekarang ke chat pasangan membacakan puisi cinta romantis yang kamu buat spontan!", false},
	{253, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Ucapkan terima kasih atas 3 hal kecil yang dilakukan pasanganmu hari ini dengan nada paling tulus!", false},
	{254, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Gombalan", "Buat gombalan maut menggunakan kata: 'Bintang', 'WiFi', dan 'Jantung' lalu sampaikan ke pasangan!", false},
	{255, "DARE", "WORDS_OF_AFFIRMATION", "OFFLINE", "Romantis", "Bisikkan ke telinga pasanganmu kalimat: 'Kamu adalah anugerah terindah yang pernah Tuhan kasih buat aku' dengan sangat lembut!", false},
	{256, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Kecup microphone HP-mu sambil bisikkan kalimat 'I miss you so much' hingga suaranya terdengar jelas oleh pasangan!", false},
	{257, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "Chat", "Tulis status WhatsApp atau status Instagram dengan 1 kalimat apresiasi termanis untuk pasanganmu sekarang!", false},
	{258, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Puji gaya pakaian atau penampilan pasanganmu hari ini layaknya seorang juri mode profesional yang terpesona!", false},
	{259, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Sebutkan 3 sifat kepribadian pasanganmu yang menurutmu paling langka dan patut dipertahankan seumur hidup!", false},
	{260, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Katakan 'Aku sayang kamu' dalam 5 bahasa daerah atau bahasa asing berbeda dengan ekspresi paling manis!", false},
	{261, "DARE", "WORDS_OF_AFFIRMATION", "OFFLINE", "Apresiasi", "Pegang kedua tangan pasangan, tatap matanya, dan katakan: 'Terima kasih sudah selalu sabar dan bertahan sama aku'!", false},
	{262, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Dekatkan wajahmu ke kamera video call (jarak 5 cm), tatap lurus dan katakan: 'Jarak ini gak akan pernah ngalahin rasa sayangku'!", false},
	{263, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Gombalan", "Tirukan adegan drama romantis di mana kamu menyatakan cinta seolah-olah baru pertama kali bertemu!", false},
	{264, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Sebutkan 3 hal yang menurutmu membuat pasanganmu 100x lebih mempesona dibanding orang lain!", false},
	{265, "DARE", "WORDS_OF_AFFIRMATION", "OFFLINE", "Romantis", "Tuliskan satu janji manis di telapak tangan pasangan menggunakan jari telunjukmu dan minta dia menebaknya!", false},
	{266, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Kirimkan pesan teks berisikan 5 alasan detail kenapa kamu memilih dia menjadi pendamping hidupmu!", false},
	{267, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Beri penghargaan imajiner (misal: 'Pasangan Paling Pengertian Sedunia') dan pidatokan pidato penyerahan penghargaannya!", false},
	{268, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Tatap mata pasanganmu selama 15 detik, lalu ungkapkan apa hal paling indah yang kamu lihat di bola matanya!", false},
	{269, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Gombalan", "Keluarkan gombalan paling receh yang kamu tahu sampai pasanganmu tertawa atau menutup wajahnya!", false},
	{270, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Ucapkan doa terbaik untuk kesehatan dan kesuksesan pasanganmu secara lisan di hadapannya sekarang!", false},
	{271, "DARE", "WORDS_OF_AFFIRMATION", "OFFLINE", "Pujian", "Dekatkan wajahmu dan puji aroma parfum atau wangi tubuh pasanganmu dengan kalimat paling puitis!", false},
	{272, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Screenshot layar video call kalian saat pasangan sedang tersenyum termanis, lalu jadikan wallpaper chat kalian!", false},
	{273, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Bikin pantun gombal 4 baris yang menggunakan nama lengkap atau nama panggilan pasanganmu!", false},
	{274, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Ceritakan satu momen di mana pasanganmu terlihat sangat cerdas atau keren di matamu!", false},
	{275, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Katakan kepada pasanganmu: 'Duniaku jauh lebih berwarna sejak ada kamu' dengan tatapan paling teduh!", false},
	{276, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Gombalan", "Pura-pura jadi pembaca berita yang memberitakan kabar gembira bahwa pasanganmu adalah manusia paling memikat hari ini!", false},
	{277, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Sebutkan 3 bagian dari senyuman pasanganmu yang paling bisa meluluhkan rasa kesal atau capekmu!", false},
	{278, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Bikin rekaman video pendek 10 detik mengucapkan 'Selamat tidur sayang, mimpi indah ya' khusus untuk dia simpan!", false},
	{279, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Katakan 1 permohonan maaf tulus atas ucapan yang mungkin pernah menyinggung perasaan pasanganmu belakangan ini!", false},
	{280, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Bandingkan kecantikan / ketampanan pasanganmu dengan tokoh idola dan jelaskan kenapa pasanganmu menang telak!", false},
	{281, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Letakkan tanganmu di dadamu dan ucapkan: 'Detak jantungku ini berdetak lebih cepat setiap kali namamu disebut'!", false},
	{282, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Gombalan", "Tanyakan tebak-tebakan romantis yang jawabannya adalah nama pasanganmu!", false},
	{283, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Puji masakan, selera musik, atau rekomendasi tontonan yang pernah diberikan oleh pasanganmu!", false},
	{284, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Panggil pasanganmu dengan 5 panggilan manja berbeda berturut-turut dalam satu tarikan napas!", false},
	{285, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Katakan: 'Kalau aku disuruh memilih lagi seribu kali, aku tetap akan memilih kamu' dengan penuh penghayatan!", false},
	{286, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Kagum", "Uraikan dalam 30 detik kenapa masa depanmu terasa jauh lebih pasti dan tenang saat ada dirinya di sampingmu!", false},
	{287, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Tatap pasanganmu dan katakan apa yang paling membuatmu merasa beruntung menjadi pasangannya!", false},
	{288, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Bikin janji lisan: 'Mulai hari ini, aku akan lebih sering memuji dan mengapresiasi usahamu'!", false},
	{289, "DARE", "WORDS_OF_AFFIRMATION", "OFFLINE", "Gombalan", "Bisikkan gombalan maut tepat di telinga pasangan sampai bulu kuduknya merinding salting!", false},
	{290, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Kirim pesan suara menyanyikan bagian reff lagu cinta favorit kalian berdua dengan penuh penghayatan!", false},
	{291, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Katakan kalimat penutup: 'Terima kasih sudah ada di dunia ini, dan terima kasih sudah memilihku'!", false},
	{292, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Ucapkan kalimat cinta dengan menggunakan bahasa daerah asal pasanganmu di depan kamera!", false},
	{293, "DARE", "WORDS_OF_AFFIRMATION", "OFFLINE", "Romantis", "Berlutut di depan pasangan seperti seorang ksatria dan bacakan deklarasi cintamu dalam 3 kalimat!", false},
	{294, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "Chat", "Ketik pesan 'I love you to the moon and back' dengan huruf kapital dan emoji hati sebanyak 10 buah!", false},
	{295, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Pujian", "Puji kemampuan pasanganmu dalam mendengarkan dan menjadi pendengar yang baik!", false},
	{296, "DARE", "WORDS_OF_AFFIRMATION", "OFFLINE", "Gombalan", "Kecup tangan pasangan lalu katakan gombalan tentang betapa lembut dan berharganya genggamannya!", false},
	{297, "DARE", "WORDS_OF_AFFIRMATION", "ONLINE", "LDR", "Tatap layar video call tanpa berkedip selama 20 detik sambil tersenyum menatap bibir pasanganmu!", false},
	{298, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Apresiasi", "Katakan apa sifat terbaik pasanganmu yang membuat keluargamu atau teman-temanmu kagum padanya!", false},
	{299, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Romantis", "Sampaikan satu kalimat penenang yang ingin selalu diingat pasangan saat dia sedang panik atau stres!", false},
	{300, "DARE", "WORDS_OF_AFFIRMATION", "BOTH", "Komitmen", "Ucapkan sumpah setia romantis yang akan selalu kamu jaga apapun tantangan yang dihadapi hubungan ini!", false},
}
